const ActionNames = {
  SetParentAndRanks: 'setParentAndRanks',
  AddTaxonStatus: 'addTaxonStatus',
  AddTaxonType: 'addTaxonType',
  AddTaxonRelationship: 'addTaxonRelationship',
  AddOriginalCombination: 'addOriginalCombination',
  AddSubsequentNameForm: 'addSubsequentNameForm',
  CloneTaxon: 'cloneTaxon',
  CreateTaxonName: 'createTaxonName',
  CreateCombination: 'createCombination',
  UpdateTaxonName: 'updateTaxonName',
  RemoveTaxonStatus: 'removeTaxonStatus',
  RemoveTaxonRelationship: 'removeTaxonRelationship',
  RemoveOriginalCombination: 'removeOriginalCombination',
  LoadCombinations: 'loadCombinations',
  LoadSoftValidation: 'loadSoftValidation',
  LoadTaxonName: 'loadTaxonName',
  LoadTaxonRelationships: 'loadTaxonRelationships',
  LoadTaxonStatus: 'loadTaxonStatus',
  LoadRanks: 'loadRanks',
  LoadStatus: 'loadStatus',
  LoadRelationships: 'loadRelationships',
  LoadOriginalCombination: 'loadOriginalCombination',
  ChangeTaxonSource: 'changeTaxonSource',
  RemoveCombination: 'removeCombination',
  RemoveSource: 'removeSource',
  UpdateClassification: 'updateClassification',
  UpdateTaxonRelationship: 'updateTaxonRelationship',
  UpdateTaxonStatus: 'updateTaxonStatus',
  UpdateTaxonType: 'updateTaxonType',
  UpdateSource: 'updateSource'
}

export default ActionNames
