const ActionNames = {
  AddToContainer: 'addToContainer',
  CreateDeterminationFromParams: 'createDeterminationFromParams',
  GetCOCitations: 'getCOCitations',
  GetCollectingEvent: 'getCollectingEvent',
  GetCollectionObject: 'getCollectionObject',
  GetIdentifier: 'getIdentifier',
  GetIdentifiers: 'getIdentifiers',
  GetLabels: 'getLabels',
  GetNamespace: 'getNamespace',
  GetTaxon: 'getTaxon',
  GetTaxonDeterminations: 'getTaxonDeterminations',
  GetTypeMaterial: 'getTypeMaterial',
  LoadGeoreferences: 'loadGeoreferences',
  LoadBiologicalAssociations: 'loadBiologicalAssociations',
  LoadContainer: 'loadContainer',
  LoadDigitalization: 'loadDigitalization',
  LoadSoftValidations: 'loadSoftValidations',
  NewCollectingEvent: 'newCollectingEvent',
  NewCollectionObject: 'newCollectionObject',
  NewIdentifier: 'newIdentifier',
  NewLabel: 'newLabel',
  NewTypeMaterial: 'newTypeMaterial',
  RemoveCOCitation: 'removeCOCitation',
  RemoveCollectionObject: 'removeCollectionObject',
  RemoveContainer: 'removeContainer',
  RemoveContainerItem: 'removeContainerItem',
  RemoveDepictionsByImageId: 'removeDepictionsByImageId',
  RemoveTaxonDetermination: 'removeTaxonDetermination',
  RemoveTypeMaterial: 'removeTypeMaterial',
  ResetTaxonDetermination: 'resetTaxonDetermination',
  ResetWithDefault: 'resetWithDefault',
  SaveBiologicalAssociations: 'saveBiologicalAssociation',
  SaveCOCitations: 'saveCOCitations',
  SaveCollectingEvent: 'saveCollectingEvent',
  SaveCollectionObject: 'saveCollectionObject',
  SaveContainer: 'saveContainer',
  SaveContainerItem: 'saveContainerItem',
  SaveDeterminations: 'saveDeterminations',
  SaveDigitalization: 'saveDigitalization',
  SaveIdentifier: 'saveIdentifier',
  SaveLabel: 'saveLabel',
  SaveTypeMaterial: 'saveTypeMaterial',
  UpdateLayoutPreferences: 'updateLayoutPreferences'
}

export default ActionNames
