const ActionNames = {
  AddToContainer: 'addToContainer',
  AddTypeSpecimen: 'addTypeSpecimen',
  GetCOCitations: 'getCOCitations',
  GetCollectionObject: 'getCollectionObject',
  SetTypeMaterial: 'setTypeMaterial',
  SetTypeMaterialTaxonName: 'setTypeMaterialTaxonName',
  LoadTypeSpecimens: 'loadTypeSpecimens',
  LoadContainer: 'loadContainer',
  LoadDigitalization: 'loadDigitalization',
  LoadSoftValidations: 'loadSoftValidations',
  NewCollectionObject: 'newCollectionObject',
  NewTypeMaterial: 'newTypeMaterial',
  RemoveCOCitation: 'removeCOCitation',
  RemoveCollectionObject: 'removeCollectionObject',
  RemoveContainer: 'removeContainer',
  RemoveContainerItem: 'removeContainerItem',
  RemoveDepictionsByImageId: 'removeDepictionsByImageId',
  RemoveTypeMaterial: 'removeTypeMaterial',
  ResetStore: 'resetStore',
  ResetWithDefault: 'resetWithDefault',
  SaveCOCitations: 'saveCOCitations',
  SaveCollectionObject: 'saveCollectionObject',
  SaveContainer: 'saveContainer',
  SaveContainerItem: 'saveContainerItem',
  SaveDigitalization: 'saveDigitalization',
  SaveIdentifier: 'saveIdentifier',
  SaveTypeMaterial: 'saveTypeMaterial',
  UpdateLayoutPreferences: 'updateLayoutPreferences',
  UpdateLastChange: 'updateLastChange',
  UpdateCEChange: 'updateCEChange'
}

export default ActionNames
