const ActionNames = {
  AddToContainer: 'addToContainer',
  AddTypeSpecimen: 'addTypeSpecimen',
  CloneCollectingEvent: 'cloneCollectingEvent',
  GetCOCitations: 'getCOCitations',
  GetCollectingEvent: 'getCollectingEvent',
  GetCollectionObject: 'getCollectionObject',
  GetLabels: 'getLabels',
  GetNamespace: 'getNamespace',
  SetTypeMaterial: 'setTypeMaterial',
  SetTypeMaterialTaxonName: 'setTypeMaterialTaxonName',
  LoadTypeSpecimens: 'loadTypeSpecimens',
  LoadGeoreferences: 'loadGeoreferences',
  LoadBiologicalAssociations: 'loadBiologicalAssociations',
  LoadContainer: 'loadContainer',
  LoadDigitalization: 'loadDigitalization',
  LoadSoftValidations: 'loadSoftValidations',
  NewCollectingEvent: 'newCollectingEvent',
  NewCollectionObject: 'newCollectionObject',
  NewIdentifier: 'newIdentifier',
  NewLabel: 'newLabel',
  NewTypeMaterial: 'newTypeMaterial',
  RemoveCOCitation: 'removeCOCitation',
  RemoveCollectionObject: 'removeCollectionObject',
  RemoveContainer: 'removeContainer',
  RemoveContainerItem: 'removeContainerItem',
  RemoveDepictionsByImageId: 'removeDepictionsByImageId',
  RemoveTypeMaterial: 'removeTypeMaterial',
  ResetStore: 'resetStore',
  ResetWithDefault: 'resetWithDefault',
  SaveBiologicalAssociations: 'saveBiologicalAssociation',
  SaveCOCitations: 'saveCOCitations',
  SaveCollectingEvent: 'saveCollectingEvent',
  SaveCollectionObject: 'saveCollectionObject',
  SaveContainer: 'saveContainer',
  SaveContainerItem: 'saveContainerItem',
  SaveDigitalization: 'saveDigitalization',
  SaveIdentifier: 'saveIdentifier',
  SaveLabel: 'saveLabel',
  SaveTypeMaterial: 'saveTypeMaterial',
  UpdateLayoutPreferences: 'updateLayoutPreferences',
  UpdateLastChange: 'updateLastChange',
  UpdateCEChange: 'updateCEChange'
}

export default ActionNames
