# lib/autoselect/levels/smart.rb
#
# Default level that delegates to the existing Queries::<Model>::Autocomplete class.
# Wraps all existing autocomplete logic and makes it available as a level.
# Generated by default for all model autoselects.
#
# Subclasses must override #query_class to specify the concrete Query class.
#
class Autoselect::Levels::Smart < Autoselect::Level

  RECENT_LIMIT = 10
  RECENT_WINDOW = 1.week

  # @return [Class] the Queries::<Model>::Autocomplete class to delegate to
  def query_class
    raise NotImplementedError, "#{self.class} must implement #query_class"
  end

  def key
    :smart
  end

  def label
    'Smart'
  end

  def description
    'Multi-query results with fuzzy and pattern matching.'
  end

  # @param term [String]
  # @param operator [Symbol, nil] :recent, :recent_mine, :pinboard, :pinboard_top, or nil
  # @param project_id [Integer, nil]
  # @param user_id [Integer, nil]
  # @param kwargs [Hash] passed through to the query class
  # @return [Array] of ActiveRecord model instances
  def call(term:, operator: nil, project_id: nil, user_id: nil, **kwargs)
    case operator
    when :recent
      recent_records(project_id:)
    when :recent_mine
      recent_records_by_user(project_id:, user_id:)
    when :pinboard
      pinboard_records(project_id:, user_id:)
    when :pinboard_top
      pinboard_top_record(project_id:, user_id:)
    else
      query_class.new(term, project_id:, **kwargs).autocomplete
    end
  end

  private

  # TODO: abstract to a recent concern if it doesn't already exist
  #
  # Records updated in the last week by anyone in the project, most recent first.
  # Delegates to the model Filter so project_id scoping is handled correctly
  # for models that may not have a project_id column.
  def recent_records(project_id:)
    return [] if project_id.blank?
    filter_class.new(
      project_id:,
      updated_since: RECENT_WINDOW.ago.to_date.iso8601
    ).all.order(updated_at: :desc).limit(RECENT_LIMIT).to_a
  end

  # TODO: See existing recent records, or abstract this to a Recent concern
  # Records updated in the last week by the given user, most recent first.
  def recent_records_by_user(project_id:, user_id:)
    return [] if project_id.blank? || user_id.blank?
    filter_class.new(
      project_id:,
      updated_since: RECENT_WINDOW.ago.to_date.iso8601,
      user_id:,
      user_target: 'updated'
    ).all.order(updated_at: :desc).limit(RECENT_LIMIT).to_a
  end

  # All pinboard items for this model type, ordered by pin position.
  def pinboard_records(project_id:, user_id:)
    return [] if user_id.blank?
    ::PinboardItem
      .where(pinned_object_type: pinboard_model_name, user_id:, project_id:)
      .order(:position)
      .includes(:pinned_object)
      .map(&:pinned_object)
      .compact
  end

  # The topmost pinboard item for this model type (0 or 1 records).
  def pinboard_top_record(project_id:, user_id:)
    rec = pinboard_records(project_id:, user_id:).first
    rec ? [rec] : []
  end

  # Derive the AR model name from the query class namespace.
  # Queries::TaxonName::Autocomplete → 'TaxonName'
  def pinboard_model_name
    query_class.name.split('::')[-2]
  end

  # Derive the Filter class from the query_class namespace.
  # e.g. Queries::TaxonName::Autocomplete -> Queries::TaxonName::Filter
  def filter_class
    parts = query_class.name.split('::')
    parts[-1] = 'Filter'
    parts.join('::').constantize
  end

end
