import {
  ALTERNATE_VALUE,
  ANATOMICAL_PART,
  ASSERTED_DISTRIBUTION,
  ASSERTED_ENVIRONMENT,
  ATTRIBUTION,
  BIOLOGICAL_ASSOCIATION,
  CHARACTER_STATE,
  CITATION,
  COLLECTING_EVENT,
  COLLECTION_OBJECT,
  CONFIDENCE,
  CONTENT,
  CONTROLLED_VOCABULARY_TERM,
  DATA_ATTRIBUTE,
  DESCRIPTOR,
  DOCUMENTATION,
  DWC_OCCURRENCE,
  EXTRACT,
  FIELD_OCCURRENCE,
  IDENTIFIER,
  IMAGE,
  LEAD,
  LOAN,
  NOTE,
  OBSERVATION,
  OTU,
  PERSON,
  SEQUENCE,
  SOUND,
  SOURCE,
  TAG,
  TAXON_NAME,
  TAXON_NAME_RELATIONSHIP
} from '@/constants/index.js'

export const ID_PARAM_FOR = {
  [ALTERNATE_VALUE]: 'alternate_value_id',
  [ANATOMICAL_PART]: 'anatomical_part_id',
  [ASSERTED_DISTRIBUTION]: 'asserted_distribution_id',
  [ASSERTED_ENVIRONMENT]: 'asserted_environment_id',
  [ATTRIBUTION]: 'attribution_id',
  [BIOLOGICAL_ASSOCIATION]: 'biological_association_id',
  [CHARACTER_STATE]: 'character_state_id',
  [CITATION]: 'citation_id',
  [COLLECTING_EVENT]: 'collecting_event_id',
  [COLLECTION_OBJECT]: 'collection_object_id',
  [CONFIDENCE]: 'confidence_id',
  [CONTENT]: 'content_id',
  [CONTROLLED_VOCABULARY_TERM]: 'controlled_vocabulary_term_id',
  [DATA_ATTRIBUTE]: 'data_attribute_id',
  [DESCRIPTOR]: 'descriptor_id',
  [DOCUMENTATION]: 'documentation_id',
  [DWC_OCCURRENCE]: 'dwc_occurrence_id',
  [EXTRACT]: 'extract_id',
  [FIELD_OCCURRENCE]: 'field_occurrence_id',
  [IDENTIFIER]: 'identifier_id',
  [IMAGE]: 'image_id',
  [LEAD]: 'lead_id',
  [LOAN]: 'loan_id',
  [NOTE]: 'note_id',
  [OBSERVATION]: 'observation_id',
  [OTU]: 'otu_id',
  [PERSON]: 'person_id',
  [SEQUENCE]: 'sequence_id',
  [SOUND]: 'sound_id',
  [SOURCE]: 'source_id',
  [TAG]: 'tag_id',
  [TAXON_NAME]: 'taxon_name_id',
  [TAXON_NAME_RELATIONSHIP]: 'taxon_name_relationship_id'
}
