import {
  ASSERTED_DISTRIBUTION,
  BIOLOGICAL_ASSOCIATION,
  CHARACTER_STATE,
  COLLECTING_EVENT,
  COLLECTION_OBJECT,
  CONTENT,
  DESCRIPTOR,
  DWC_OCCURRENCE,
  EXTRACT,
  FIELD_OCCURRENCE,
  IMAGE,
  LOAN,
  OBSERVATION,
  OTU,
  PERSON,
  SOUND,
  SOURCE,
  TAXON_NAME,
  TAXON_NAME_RELATIONSHIP
} from '@/constants/index.js'

export const ID_PARAM_FOR = {
  [ASSERTED_DISTRIBUTION]: 'asserted_distribution_id',
  [BIOLOGICAL_ASSOCIATION]: 'biological_association_id',
  [CHARACTER_STATE]: 'character_state_id',
  [COLLECTING_EVENT]: 'collecting_event_id',
  [COLLECTION_OBJECT]: 'collection_object_id',
  [CONTENT]: 'content_id',
  [DESCRIPTOR]: 'descriptor_id',
  [DWC_OCCURRENCE]: 'dwc_occurrence_id',
  [EXTRACT]: 'extract_id',
  [FIELD_OCCURRENCE]: 'field_occurrence_id',
  [IMAGE]: 'image_id',
  [LOAN]: 'loan_id',
  [OBSERVATION]: 'observation_id',
  [OTU]: 'otu_id',
  [PERSON]: 'person_id',
  [SOUND]: 'sound_id',
  [SOURCE]: 'source_id',
  [TAXON_NAME]: 'taxon_name_id',
  [TAXON_NAME_RELATIONSHIP]: 'taxon_name_relationship_id'
}
