import {
  ALTERNATE_VALUE,
  ANATOMICAL_PART,
  ASSERTED_DISTRIBUTION,
  ASSERTED_ENVIRONMENT,
  ATTRIBUTION,
  BIOLOGICAL_ASSOCIATION,
  CITATION,
  COLLECTING_EVENT,
  COLLECTION_OBJECT,
  CONFIDENCE,
  CONTENT,
  DATA_ATTRIBUTE,
  DESCRIPTOR,
  DOCUMENTATION,
  DWC_OCCURRENCE,
  EXTRACT,
  FIELD_OCCURRENCE,
  IDENTIFIER,
  IMAGE,
  LEAD,
  LOAN,
  NOTE,
  OBSERVATION,
  OTU,
  PERSON,
  SOUND,
  SOURCE,
  TAG,
  TAXON_NAME,
  TAXON_NAME_RELATIONSHIP
} from '@/constants/index.js'

export const QUERY_PARAM = {
  [ALTERNATE_VALUE]: 'alternate_value_query',
  [ANATOMICAL_PART]: 'anatomical_part_query',
  [ASSERTED_DISTRIBUTION]: 'asserted_distribution_query',
  [ASSERTED_ENVIRONMENT]: 'asserted_environment_query',
  [ATTRIBUTION]: 'attribution_query',
  [BIOLOGICAL_ASSOCIATION]: 'biological_association_query',
  [CITATION]: 'citation_query',
  [COLLECTING_EVENT]: 'collecting_event_query',
  [COLLECTION_OBJECT]: 'collection_object_query',
  [CONFIDENCE]: 'confidence_query',
  [CONTENT]: 'content_query',
  [DATA_ATTRIBUTE]: 'data_attribute_query',
  [DESCRIPTOR]: 'descriptor_query',
  [DOCUMENTATION]: 'documentation_query',
  [DWC_OCCURRENCE]: 'dwc_occurrence_query',
  [EXTRACT]: 'extract_query',
  [FIELD_OCCURRENCE]: 'field_occurrence_query',
  [IDENTIFIER]: 'identifier_query',
  [IMAGE]: 'image_query',
  [LEAD]: 'lead_query',
  [LOAN]: 'loan_query',
  [NOTE]: 'note_query',
  [OBSERVATION]: 'observation_query',
  [OTU]: 'otu_query',
  [PERSON]: 'person_query',
  [SOUND]: 'sound_query',
  [SOURCE]: 'source_query',
  [TAG]: 'tag_query',
  [TAXON_NAME]: 'taxon_name_query',
  [TAXON_NAME_RELATIONSHIP]: 'taxon_name_relationship_query'
}
