import {
  OBSERVATION_MATRIX_COLUMN_DYNAMIC_TAG,
  OBSERVATION_MATRIX_COLUMN_SINGLE_DESCRIPTOR,
  OBSERVATION_MATRIX_ROW_DYNAMIC_TAXONNAME,
  OBSERVATION_MATRIX_ROW_SINGLE_COLLECTION_OBJECT,
  OBSERVATION_MATRIX_ROW_SINGLE_OTU,
  OBSERVATION_MATRIX_ROW_DYNAMIC_TAG
} from 'constants/index.js'

export default {
  Row: {
    Tag: OBSERVATION_MATRIX_ROW_DYNAMIC_TAG,
    TaxonName: OBSERVATION_MATRIX_ROW_DYNAMIC_TAXONNAME,
    Otu: OBSERVATION_MATRIX_ROW_SINGLE_OTU,
    CollectionObject: OBSERVATION_MATRIX_ROW_SINGLE_COLLECTION_OBJECT
  },
  Column: {
    Descriptor: OBSERVATION_MATRIX_COLUMN_SINGLE_DESCRIPTOR,
    Tag: OBSERVATION_MATRIX_COLUMN_DYNAMIC_TAG
  }
}
