// Update corresponding at SUBQUERIES in /lib/queries/query/filter.rb
import {
  FILTER_BIOLOGICAL_ASSOCIATION,
  FILTER_COLLECTION_OBJECT,
  FILTER_EXTRACT,
  FILTER_FIELD_OCCURRENCE,
  FILTER_OBSERVATION,
  FILTER_OTU,
  FILTER_SOUND
} from '../constants/filterLinks'

export const AnatomicalPart = [
  FILTER_BIOLOGICAL_ASSOCIATION,
  FILTER_COLLECTION_OBJECT,
  FILTER_EXTRACT,
  FILTER_FIELD_OCCURRENCE,
  FILTER_OBSERVATION,
  FILTER_OTU,
  FILTER_SOUND
]
