// Update corresponding at SUBQUERIES in /lib/queries/query/filter.rb
import {
  FILTER_BIOLOGICAL_ASSOCIATION,
  FILTER_CITATION,
  FILTER_COLLECTION_OBJECT,
  FILTER_CONFIDENCE,
  FILTER_EXTRACT,
  FILTER_FIELD_OCCURRENCE,
  FILTER_IDENTIFIER,
  FILTER_NOTE,
  FILTER_OBSERVATION,
  FILTER_OTU,
  FILTER_SOUND,
  FILTER_TAG
} from '../constants/filterLinks'

export const AnatomicalPart = [
  FILTER_BIOLOGICAL_ASSOCIATION,
  FILTER_CITATION,
  FILTER_COLLECTION_OBJECT,
  FILTER_CONFIDENCE,
  FILTER_EXTRACT,
  FILTER_FIELD_OCCURRENCE,
  FILTER_IDENTIFIER,
  FILTER_NOTE,
  FILTER_OBSERVATION,
  FILTER_OTU,
  FILTER_SOUND,
  FILTER_TAG
]
