import {
  FILTER_OTU,
  FILTER_SOURCE,
  FILTER_TAXON_NAME,
  FILTER_BIOLOGICAL_ASSOCIATION,
  FILTER_DWC_OCCURRENCE
} from '../constants/filterLinks'

export const AssertedDistribution = [
  FILTER_SOURCE,
  FILTER_OTU,
  FILTER_TAXON_NAME,
  FILTER_BIOLOGICAL_ASSOCIATION,
  FILTER_DWC_OCCURRENCE
]
