import {
  FILTER_CITATION,
  FILTER_COLLECTING_EVENT,
  FILTER_DATA_ATTRIBUTE,
  FILTER_IDENTIFIER,
  FILTER_NOTE,
  FILTER_OTU,
  FILTER_TAG
} from '../constants/filterLinks'

export const AssertedEnvironment = [
  FILTER_CITATION,
  FILTER_COLLECTING_EVENT,
  FILTER_DATA_ATTRIBUTE,
  FILTER_IDENTIFIER,
  FILTER_NOTE,
  FILTER_OTU,
  FILTER_TAG
]
