import {
  FILTER_BIOLOGICAL_ASSOCIATION,
  FILTER_CITATION,
  FILTER_DWC_OCCURRENCE,
  FILTER_OBSERVATION,
  FILTER_OTU,
  FILTER_SOURCE,
  FILTER_TAXON_NAME,
} from '../constants/filterLinks'

export const AssertedDistribution = [
  FILTER_BIOLOGICAL_ASSOCIATION,
  FILTER_CITATION,
  FILTER_DWC_OCCURRENCE,
  FILTER_OBSERVATION,
  FILTER_OTU,
  FILTER_SOURCE,
  FILTER_TAXON_NAME,
]
