import {
  FILTER_SOURCE,

  FILTER_TAXON_NAME,
  FILTER_COLLECTING_EVENT,
  FILTER_COLLECTION_OBJECT,
  FILTER_OTU,
  FILTER_ASSERTED_DISTRIBUTION,
} from '../constants/filterLinks'

export const BiologicalAssociation = {
  all: [
    FILTER_SOURCE,
    FILTER_TAXON_NAME,
    FILTER_ASSERTED_DISTRIBUTION,
    FILTER_COLLECTION_OBJECT,
    FILTER_COLLECTING_EVENT,
    FILTER_OTU,
  ],
  ids: [
    FILTER_OTU,
  ]
}
