import {
  FILTER_ASSERTED_DISTRIBUTION,
  FILTER_COLLECTING_EVENT,
  FILTER_COLLECTION_OBJECT,
  FILTER_OTU,
  FILTER_SOURCE,
  FILTER_TAXON_NAME,
  FILTER_FIELD_OCCURRENCE
} from '../constants/filterLinks'

export const BiologicalAssociation = [
  FILTER_ASSERTED_DISTRIBUTION,
  FILTER_COLLECTING_EVENT,
  FILTER_COLLECTION_OBJECT,
  FILTER_OTU,
  FILTER_SOURCE,
  FILTER_TAXON_NAME,
  FILTER_FIELD_OCCURRENCE
]
