// Update corresponding at SUBQUERIES in /lib/queries/query/filter.rb
import {
  FILTER_ANATOMICAL_PART,
  FILTER_BIOLOGICAL_ASSOCIATION,
  FILTER_CITATION,
  FILTER_COLLECTING_EVENT,
  FILTER_DWC_OCCURRENCE,
  FILTER_EXTRACT,
  FILTER_IMAGE,
  FILTER_LOAN,
  FILTER_OBSERVATION,
  FILTER_OTU,
  FILTER_SOURCE,
  FILTER_TAXON_NAME,
} from '../constants/filterLinks'

export const CollectionObject = [
  FILTER_ANATOMICAL_PART,
  FILTER_BIOLOGICAL_ASSOCIATION,
  FILTER_CITATION,
  FILTER_COLLECTING_EVENT,
  FILTER_DWC_OCCURRENCE,
  FILTER_EXTRACT,
  FILTER_IMAGE,
  FILTER_LOAN,
  FILTER_OBSERVATION,
  FILTER_OTU,
  FILTER_SOURCE,
  FILTER_TAXON_NAME,
]
