import { FILTER_LINKS } from '../constants/filterLinks'
import {
  COLLECTING_EVENT,
  SOURCE,
  IMAGE,
  TAXON_NAME,
  OTU,
  BIOLOGICAL_ASSOCIATION
} from 'constants/index.js'

export const CollectionObject = [
  FILTER_LINKS[OTU],
  FILTER_LINKS[TAXON_NAME],
  FILTER_LINKS[COLLECTING_EVENT],
  FILTER_LINKS[SOURCE],
  FILTER_LINKS[BIOLOGICAL_ASSOCIATION],
  FILTER_LINKS[IMAGE]
]
