// Update corresponding at SUBQUERIES in /lib/queries/query/filter.rb
import {
  FILTER_BIOLOGICAL_ASSOCIATION,
  FILTER_CITATION,
  FILTER_COLLECTION_OBJECT,
  FILTER_CONFIDENCE,
  FILTER_DATA_ATTRIBUTE,
  FILTER_DOCUMENTATION,
  FILTER_DWC_OCCURRENCE,
  FILTER_FIELD_OCCURRENCE,
  FILTER_IDENTIFIER,
  FILTER_IMAGE,
  FILTER_NOTE,
  FILTER_OTU,
  FILTER_SOURCE,
  FILTER_TAG,
  FILTER_TAXON_NAME
} from '../constants/filterLinks'

export const CollectingEvent = [
  FILTER_BIOLOGICAL_ASSOCIATION,
  FILTER_CITATION,
  FILTER_COLLECTION_OBJECT,
  FILTER_CONFIDENCE,
  FILTER_DATA_ATTRIBUTE,
  FILTER_DOCUMENTATION,
  FILTER_DWC_OCCURRENCE,
  FILTER_FIELD_OCCURRENCE,
  FILTER_IDENTIFIER,
  FILTER_IMAGE,
  FILTER_NOTE,
  FILTER_OTU,
  FILTER_SOURCE,
  FILTER_TAG,
  FILTER_TAXON_NAME
]
