// Update corresponding at SUBQUERIES in /lib/queries/query/filter.rb
import {
  FILTER_BIOLOGICAL_ASSOCIATION,
  FILTER_COLLECTION_OBJECT,
  FILTER_IMAGE,
  FILTER_OTU,
  FILTER_SOURCE,
  FILTER_TAXON_NAME,
} from '../constants/filterLinks'

export const CollectingEvent = {
  all: [
    FILTER_BIOLOGICAL_ASSOCIATION,
    FILTER_COLLECTION_OBJECT,
    FILTER_OTU,
    FILTER_SOURCE,
    FILTER_TAXON_NAME,
  ],
  ids: [
    FILTER_BIOLOGICAL_ASSOCIATION,
    FILTER_COLLECTION_OBJECT,
    FILTER_OTU,
    FILTER_TAXON_NAME,
    FILTER_IMAGE,
  ]
}
