import {
  FILTER_ASSERTED_ENVIRONMENT,
  FILTER_COLLECTING_EVENT,
  FILTER_COLLECTION_OBJECT,
  FILTER_FIELD_OCCURRENCE,
  FILTER_LEAD,
  FILTER_OTU,
  FILTER_TAXON_NAME
} from '../constants/filterLinks'

export const DataAttribute = [
  FILTER_ASSERTED_ENVIRONMENT,
  FILTER_COLLECTING_EVENT,
  FILTER_COLLECTION_OBJECT,
  FILTER_FIELD_OCCURRENCE,
  FILTER_LEAD,
  FILTER_OTU,
  FILTER_TAXON_NAME
]
