import {
  FILTER_ALTERNATE_VALUE,
  FILTER_CITATION,
  FILTER_CONFIDENCE,
  FILTER_DOCUMENTATION,
  FILTER_IDENTIFIER,
  FILTER_NOTE,
  FILTER_OBSERVATION,
  FILTER_OTU,
  FILTER_SOURCE,
  FILTER_TAG,
} from '../constants/filterLinks'

export const Descriptor = [
  FILTER_ALTERNATE_VALUE,
  FILTER_CITATION,
  FILTER_CONFIDENCE,
  FILTER_DOCUMENTATION,
  FILTER_IDENTIFIER,
  FILTER_NOTE,
  FILTER_OBSERVATION,
  FILTER_OTU,
  FILTER_SOURCE,
  FILTER_TAG
]
