// Update corresponding at SUBQUERIES in /lib/queries/query/filter.rb
import {
  FILTER_COLLECTION_OBJECT,
  FILTER_COLLECTING_EVENT,
  FILTER_ASSERTED_DISTRIBUTION,
  FILTER_FIELD_OCCURRENCE,
  FILTER_OTU,
} from '../constants/filterLinks'

export const DwcOccurrence = [
  FILTER_COLLECTION_OBJECT,
  FILTER_COLLECTING_EVENT,
  FILTER_ASSERTED_DISTRIBUTION,
  FILTER_FIELD_OCCURRENCE,
  FILTER_OTU
]
