import {
  FILTER_OBSERVATION,
  FILTER_OTU,
  FILTER_SOURCE,
  FILTER_COLLECTION_OBJECT
} from '../constants/filterLinks'

export const Extract = [FILTER_OBSERVATION, FILTER_OTU, FILTER_SOURCE, FILTER_COLLECTION_OBJECT]
