import {
  FILTER_ANATOMICAL_PART,
  FILTER_CITATION,
  FILTER_COLLECTION_OBJECT,
  FILTER_OBSERVATION,
  FILTER_OTU,
  FILTER_SOURCE,
} from '../constants/filterLinks'

export const Extract = [
  FILTER_ANATOMICAL_PART,
  FILTER_CITATION,
  FILTER_COLLECTION_OBJECT,
  FILTER_OBSERVATION,
  FILTER_OTU,
  FILTER_SOURCE,
]
