import {
  FILTER_ANATOMICAL_PART,
  FILTER_CITATION,
  FILTER_COLLECTION_OBJECT,
  FILTER_CONFIDENCE,
  FILTER_IDENTIFIER,
  FILTER_OBSERVATION,
  FILTER_OTU,
  FILTER_SOURCE,
  FILTER_TAG,
} from '../constants/filterLinks'

export const Extract = [
  FILTER_ANATOMICAL_PART,
  FILTER_CITATION,
  FILTER_COLLECTION_OBJECT,
  FILTER_CONFIDENCE,
  FILTER_IDENTIFIER,
  FILTER_OBSERVATION,
  FILTER_OTU,
  FILTER_SOURCE,
  FILTER_TAG,
]
