import {
  FILTER_ANATOMICAL_PART,
  FILTER_BIOLOGICAL_ASSOCIATION,
  FILTER_COLLECTING_EVENT,
  FILTER_DWC_OCCURRENCE,
  FILTER_IMAGE,
  FILTER_OBSERVATION,
  FILTER_OTU
} from '../constants/filterLinks'

export const FieldOccurrence = [
  FILTER_ANATOMICAL_PART,
  FILTER_BIOLOGICAL_ASSOCIATION,
  FILTER_COLLECTING_EVENT,
  FILTER_DWC_OCCURRENCE,
  FILTER_IMAGE,
  FILTER_OBSERVATION,
  FILTER_OTU
]
