import {
  FILTER_BIOLOGICAL_ASSOCIATION,
  FILTER_COLLECTING_EVENT,
  FILTER_OTU
} from '../constants/filterLinks'

export const FILTER_FIELD_OCCURRENCE = [
  FILTER_BIOLOGICAL_ASSOCIATION,
  FILTER_COLLECTING_EVENT,
  FILTER_OTU
]
