import {
  FILTER_ATTRIBUTION,
  FILTER_CITATION,
  FILTER_COLLECTING_EVENT,
  FILTER_COLLECTION_OBJECT,
  FILTER_CONTENT,
  FILTER_FIELD_OCCURRENCE,
  FILTER_IDENTIFIER,
  FILTER_NOTE,
  FILTER_OBSERVATION,
  FILTER_OTU,
  FILTER_SOURCE,
  FILTER_TAG,
  FILTER_TAXON_NAME
} from '../constants/filterLinks'

export const Image = [
  FILTER_ATTRIBUTION,
  FILTER_CITATION,
  FILTER_COLLECTING_EVENT,
  FILTER_COLLECTION_OBJECT,
  FILTER_CONTENT,
  FILTER_FIELD_OCCURRENCE,
  FILTER_IDENTIFIER,
  FILTER_NOTE,
  FILTER_OBSERVATION,
  FILTER_OTU,
  FILTER_SOURCE,
  FILTER_TAG,
  FILTER_TAXON_NAME
]
