import {
  FILTER_COLLECTING_EVENT,
  FILTER_COLLECTION_OBJECT,
  FILTER_CONTENT,
  FILTER_DESCRIPTOR,
  FILTER_OBSERVATION,
  FILTER_OTU,
  FILTER_SOURCE,
  FILTER_TAXON_NAME,
} from '../constants/filterLinks'

export const Image = {
  all: [
    FILTER_COLLECTING_EVENT,
    FILTER_COLLECTION_OBJECT,
    FILTER_CONTENT,
    FILTER_DESCRIPTOR,
    FILTER_OBSERVATION,
    FILTER_OTU,
    FILTER_SOURCE,
    FILTER_TAXON_NAME,
  ],
  ids: [ // handled in /lib/queries/concerns/depictions.rb
    FILTER_COLLECTING_EVENT,
    FILTER_COLLECTION_OBJECT,
    FILTER_CONTENT,
    FILTER_DESCRIPTOR,
    FILTER_OBSERVATION,
    FILTER_OTU,
    FILTER_SOURCE,
    FILTER_TAXON_NAME,
  ]
}