import {
    FILTER_COLLECTION_OBJECT,
    FILTER_DESCRIPTOR,
    FILTER_EXTRACT,
    FILTER_IMAGE,
    FILTER_OTU,
    FILTER_SOURCE,
} from '../constants/filterLinks'

export const Observation = [
    FILTER_COLLECTION_OBJECT,
    FILTER_DESCRIPTOR,
    FILTER_EXTRACT,
    FILTER_IMAGE,
    FILTER_OTU,
    FILTER_SOURCE,
]
