import {
    FILTER_COLLECTION_OBJECT,
    FILTER_DESCRIPTOR,
    FILTER_EXTRACT,
    FILTER_FIELD_OCCURRENCE,
    FILTER_IMAGE,
    FILTER_OTU,
    FILTER_SOUND,
    FILTER_SOURCE,
    FILTER_ASSERTED_DISTRIBUTION,
} from '../constants/filterLinks'

export const Observation = [
    FILTER_COLLECTION_OBJECT,
    FILTER_DESCRIPTOR,
    FILTER_EXTRACT,
    FILTER_FIELD_OCCURRENCE,
    FILTER_IMAGE,
    FILTER_OTU,
    FILTER_SOUND,
    FILTER_SOURCE,
    FILTER_ASSERTED_DISTRIBUTION,
]
