import { FILTER_LINKS } from '../constants/filterLinks'
import {
  COLLECTION_OBJECT,
  COLLECTING_EVENT,
  SOURCE,
  TAXON_NAME,
  PEOPLE,
  EXTRACT,
  IMAGE,
  BIOLOGICAL_ASSOCIATION,
  ASSERTED_DISTRIBUTION
} from 'constants/index.js'

export const Otu = [
  FILTER_LINKS[COLLECTION_OBJECT],
  FILTER_LINKS[COLLECTING_EVENT],
  FILTER_LINKS[TAXON_NAME],
  FILTER_LINKS[SOURCE],
  FILTER_LINKS[PEOPLE],
  FILTER_LINKS[EXTRACT],
  FILTER_LINKS[IMAGE],
  FILTER_LINKS[BIOLOGICAL_ASSOCIATION],
  FILTER_LINKS[ASSERTED_DISTRIBUTION]
]
