import {
  FILTER_ANATOMICAL_PART,
  FILTER_ASSERTED_DISTRIBUTION,
  FILTER_BIOLOGICAL_ASSOCIATION,
  FILTER_COLLECTING_EVENT,
  FILTER_COLLECTION_OBJECT,
  FILTER_CONTENT,
  FILTER_DESCRIPTOR,
  FILTER_EXTRACT,
  FILTER_IMAGE,
  FILTER_LOAN,
  FILTER_OBSERVATION,
  FILTER_SOUND,
  FILTER_SOURCE,
  FILTER_TAXON_NAME,
  FILTER_FIELD_OCCURRENCE
} from '../constants/filterLinks'

export const Otu = [
  FILTER_ANATOMICAL_PART,
  FILTER_ASSERTED_DISTRIBUTION,
  FILTER_BIOLOGICAL_ASSOCIATION,
  FILTER_COLLECTING_EVENT,
  FILTER_COLLECTION_OBJECT,
  FILTER_CONTENT,
  FILTER_DESCRIPTOR,
  FILTER_EXTRACT,
  FILTER_FIELD_OCCURRENCE,
  FILTER_IMAGE,
  FILTER_LOAN,
  FILTER_OBSERVATION,
  FILTER_SOUND,
  FILTER_SOURCE,
  FILTER_TAXON_NAME
]
