import { FILTER_LINKS } from '../constants/filterLinks'

import {
  SOURCE,
  TAXON_NAME,
  ASSERTED_DISTRIBUTION,
  BIOLOGICAL_ASSOCIATION,
  IMAGE,
  COLLECTING_EVENT,
  COLLECTION_OBJECT,
  EXTRACT,
} from 'constants/index.js'

export const Otu = {
  all: [
    FILTER_LINKS[ASSERTED_DISTRIBUTION],
    FILTER_LINKS[BIOLOGICAL_ASSOCIATION],
    FILTER_LINKS[COLLECTING_EVENT],
    FILTER_LINKS[COLLECTION_OBJECT],
    FILTER_LINKS[EXTRACT],
    FILTER_LINKS[IMAGE],
    FILTER_LINKS[SOURCE],
    FILTER_LINKS[TAXON_NAME],
  ],
  ids: [
  ]
}