import {
  FILTER_ANATOMICAL_PART,
  FILTER_ATTRIBUTION,
  FILTER_CITATION,
  FILTER_CONFIDENCE,
  FILTER_IDENTIFIER,
  FILTER_NOTE,
  FILTER_OBSERVATION,
  FILTER_OTU,
  FILTER_TAG,
  FILTER_TAXON_NAME
} from '../constants/filterLinks'

export const Sound = [
  FILTER_ANATOMICAL_PART,
  FILTER_ATTRIBUTION,
  FILTER_CITATION,
  FILTER_CONFIDENCE,
  FILTER_IDENTIFIER,
  FILTER_NOTE,
  FILTER_OBSERVATION,
  FILTER_OTU,
  FILTER_TAG,
  FILTER_TAXON_NAME
]
