import {
  FILTER_ASSERTED_DISTRIBUTION,
  FILTER_BIOLOGICAL_ASSOCIATION,
  FILTER_COLLECTING_EVENT,
  FILTER_COLLECTION_OBJECT,
  FILTER_CONTENT,
  FILTER_DESCRIPTOR,
  FILTER_EXTRACT,
  FILTER_IMAGE,
  FILTER_OBSERVATION,
  FILTER_OTU,
  FILTER_TAXON_NAME
} from '../constants/filterLinks'

export const Source = [
  FILTER_ASSERTED_DISTRIBUTION,
  FILTER_BIOLOGICAL_ASSOCIATION,
  FILTER_COLLECTING_EVENT,
  FILTER_COLLECTION_OBJECT,
  FILTER_CONTENT,
  FILTER_DESCRIPTOR,
  FILTER_EXTRACT,
  FILTER_IMAGE,
  FILTER_OBSERVATION,
  FILTER_OTU,
  FILTER_TAXON_NAME
]
