import {
  FILTER_ASSERTED_DISTRIBUTION,
  FILTER_BIOLOGICAL_ASSOCIATION,
  FILTER_COLLECTING_EVENT,
  FILTER_COLLECTION_OBJECT,
  FILTER_EXTRACT,
  FILTER_IMAGE,
  FILTER_OTU,
  FILTER_TAXON_NAME
} from '../constants/filterLinks'

export const Source = {
  all: [
    FILTER_ASSERTED_DISTRIBUTION,
    FILTER_BIOLOGICAL_ASSOCIATION,
    FILTER_COLLECTING_EVENT,
    FILTER_COLLECTION_OBJECT,
    FILTER_EXTRACT,
    FILTER_IMAGE,
    FILTER_OTU,
    FILTER_TAXON_NAME
  ],
  ids: []
}
