import {
  FILTER_ANATOMICAL_PART,
  FILTER_ASSERTED_DISTRIBUTION,
  FILTER_ASSERTED_ENVIRONMENT,
  FILTER_BIOLOGICAL_ASSOCIATION,
  FILTER_COLLECTING_EVENT,
  FILTER_COLLECTION_OBJECT,
  FILTER_DESCRIPTOR,
  FILTER_EXTRACT,
  FILTER_FIELD_OCCURRENCE,
  FILTER_IMAGE,
  FILTER_OBSERVATION,
  FILTER_OTU,
  FILTER_SOUND,
  FILTER_TAXON_NAME
} from '../constants/filterLinks'

export const Tag = [
  FILTER_ANATOMICAL_PART,
  FILTER_ASSERTED_DISTRIBUTION,
  FILTER_ASSERTED_ENVIRONMENT,
  FILTER_BIOLOGICAL_ASSOCIATION,
  FILTER_COLLECTING_EVENT,
  FILTER_COLLECTION_OBJECT,
  FILTER_DESCRIPTOR,
  FILTER_EXTRACT,
  FILTER_FIELD_OCCURRENCE,
  FILTER_IMAGE,
  FILTER_OBSERVATION,
  FILTER_OTU,
  FILTER_SOUND,
  FILTER_TAXON_NAME
]
