import {
  FILTER_ASSERTED_DISTRIBUTION,
  FILTER_BIOLOGICAL_ASSOCIATION,
  FILTER_COLLECTING_EVENT,
  FILTER_COLLECTION_OBJECT,
  FILTER_CONTENT,
  FILTER_OTU,
  FILTER_SOURCE
} from '../constants/filterLinks'

export const TaxonName = [
  FILTER_ASSERTED_DISTRIBUTION,
  FILTER_BIOLOGICAL_ASSOCIATION,
  FILTER_COLLECTING_EVENT,
  FILTER_COLLECTION_OBJECT,
  FILTER_CONTENT,
  FILTER_OTU,
  FILTER_SOURCE
]
