import {
  FILTER_BIOLOGICAL_ASSOCIATION,
  FILTER_ASSERTED_DISTRIBUTION,
  FILTER_COLLECTING_EVENT,
  FILTER_COLLECTION_OBJECT,
  FILTER_OTU,
  FILTER_SOURCE
} from '../constants/filterLinks'

export const TaxonName = {
  all: [
    FILTER_BIOLOGICAL_ASSOCIATION,
    FILTER_ASSERTED_DISTRIBUTION,
    FILTER_COLLECTING_EVENT,
    FILTER_SOURCE,
    FILTER_OTU,
    FILTER_COLLECTION_OBJECT
  ],
  ids: []
}
