import {
  FILTER_CITATION,
  FILTER_SOURCE,
  FILTER_TAXON_NAME,
  FILTER_TAXON_NAME_OBJECT,
  FILTER_TAXON_NAME_SUBJECT
} from '../constants/filterLinks'

export const TaxonNameRelationship = [
  FILTER_CITATION,
  FILTER_SOURCE,
  FILTER_TAXON_NAME,
  FILTER_TAXON_NAME_OBJECT,
  FILTER_TAXON_NAME_SUBJECT
]
