require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/anatomical_parts", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # AnatomicalPart. As you add validations to AnatomicalPart, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      AnatomicalPart.create! valid_attributes
      get anatomical_parts_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      anatomical_part = AnatomicalPart.create! valid_attributes
      get anatomical_part_url(anatomical_part)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_anatomical_part_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      anatomical_part = AnatomicalPart.create! valid_attributes
      get edit_anatomical_part_url(anatomical_part)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new AnatomicalPart" do
        expect {
          post anatomical_parts_url, params: { anatomical_part: valid_attributes }
        }.to change(AnatomicalPart, :count).by(1)
      end

      it "redirects to the created anatomical_part" do
        post anatomical_parts_url, params: { anatomical_part: valid_attributes }
        expect(response).to redirect_to(anatomical_part_url(AnatomicalPart.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new AnatomicalPart" do
        expect {
          post anatomical_parts_url, params: { anatomical_part: invalid_attributes }
        }.to change(AnatomicalPart, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post anatomical_parts_url, params: { anatomical_part: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested anatomical_part" do
        anatomical_part = AnatomicalPart.create! valid_attributes
        patch anatomical_part_url(anatomical_part), params: { anatomical_part: new_attributes }
        anatomical_part.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the anatomical_part" do
        anatomical_part = AnatomicalPart.create! valid_attributes
        patch anatomical_part_url(anatomical_part), params: { anatomical_part: new_attributes }
        anatomical_part.reload
        expect(response).to redirect_to(anatomical_part_url(anatomical_part))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        anatomical_part = AnatomicalPart.create! valid_attributes
        patch anatomical_part_url(anatomical_part), params: { anatomical_part: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested anatomical_part" do
      anatomical_part = AnatomicalPart.create! valid_attributes
      expect {
        delete anatomical_part_url(anatomical_part)
      }.to change(AnatomicalPart, :count).by(-1)
    end

    it "redirects to the anatomical_parts list" do
      anatomical_part = AnatomicalPart.create! valid_attributes
      delete anatomical_part_url(anatomical_part)
      expect(response).to redirect_to(anatomical_parts_url)
    end
  end
end
