require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/coldp_profiles", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # ColdpProfile. As you add validations to ColdpProfile, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      ColdpProfile.create! valid_attributes
      get coldp_profiles_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      coldp_profile = ColdpProfile.create! valid_attributes
      get coldp_profile_url(coldp_profile)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_coldp_profile_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      coldp_profile = ColdpProfile.create! valid_attributes
      get edit_coldp_profile_url(coldp_profile)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new ColdpProfile" do
        expect {
          post coldp_profiles_url, params: { coldp_profile: valid_attributes }
        }.to change(ColdpProfile, :count).by(1)
      end

      it "redirects to the created coldp_profile" do
        post coldp_profiles_url, params: { coldp_profile: valid_attributes }
        expect(response).to redirect_to(coldp_profile_url(ColdpProfile.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new ColdpProfile" do
        expect {
          post coldp_profiles_url, params: { coldp_profile: invalid_attributes }
        }.to change(ColdpProfile, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post coldp_profiles_url, params: { coldp_profile: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested coldp_profile" do
        coldp_profile = ColdpProfile.create! valid_attributes
        patch coldp_profile_url(coldp_profile), params: { coldp_profile: new_attributes }
        coldp_profile.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the coldp_profile" do
        coldp_profile = ColdpProfile.create! valid_attributes
        patch coldp_profile_url(coldp_profile), params: { coldp_profile: new_attributes }
        coldp_profile.reload
        expect(response).to redirect_to(coldp_profile_url(coldp_profile))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        coldp_profile = ColdpProfile.create! valid_attributes
        patch coldp_profile_url(coldp_profile), params: { coldp_profile: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested coldp_profile" do
      coldp_profile = ColdpProfile.create! valid_attributes
      expect {
        delete coldp_profile_url(coldp_profile)
      }.to change(ColdpProfile, :count).by(-1)
    end

    it "redirects to the coldp_profiles list" do
      coldp_profile = ColdpProfile.create! valid_attributes
      delete coldp_profile_url(coldp_profile)
      expect(response).to redirect_to(coldp_profiles_url)
    end
  end
end
