require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/field_occurrences", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # FieldOccurrence. As you add validations to FieldOccurrence, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      FieldOccurrence.create! valid_attributes
      get field_occurrences_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      field_occurrence = FieldOccurrence.create! valid_attributes
      get field_occurrence_url(field_occurrence)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_field_occurrence_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      field_occurrence = FieldOccurrence.create! valid_attributes
      get edit_field_occurrence_url(field_occurrence)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new FieldOccurrence" do
        expect {
          post field_occurrences_url, params: { field_occurrence: valid_attributes }
        }.to change(FieldOccurrence, :count).by(1)
      end

      it "redirects to the created field_occurrence" do
        post field_occurrences_url, params: { field_occurrence: valid_attributes }
        expect(response).to redirect_to(field_occurrence_url(FieldOccurrence.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new FieldOccurrence" do
        expect {
          post field_occurrences_url, params: { field_occurrence: invalid_attributes }
        }.to change(FieldOccurrence, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post field_occurrences_url, params: { field_occurrence: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested field_occurrence" do
        field_occurrence = FieldOccurrence.create! valid_attributes
        patch field_occurrence_url(field_occurrence), params: { field_occurrence: new_attributes }
        field_occurrence.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the field_occurrence" do
        field_occurrence = FieldOccurrence.create! valid_attributes
        patch field_occurrence_url(field_occurrence), params: { field_occurrence: new_attributes }
        field_occurrence.reload
        expect(response).to redirect_to(field_occurrence_url(field_occurrence))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        field_occurrence = FieldOccurrence.create! valid_attributes
        patch field_occurrence_url(field_occurrence), params: { field_occurrence: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested field_occurrence" do
      field_occurrence = FieldOccurrence.create! valid_attributes
      expect {
        delete field_occurrence_url(field_occurrence)
      }.to change(FieldOccurrence, :count).by(-1)
    end

    it "redirects to the field_occurrences list" do
      field_occurrence = FieldOccurrence.create! valid_attributes
      delete field_occurrence_url(field_occurrence)
      expect(response).to redirect_to(field_occurrences_url)
    end
  end
end
