import {
  TASK_COMPACT_DWC,
  TASK_FIELD_SYNCHRONIZE,
  TASK_MULTI_UPDATE,
  TASK_TYPE_MATERIAL_DASHBOARD,
} from "../constants/links";

export const AssertedDistribution = {
  all: [
    TASK_COMPACT_DWC,
    TASK_FIELD_SYNCHRONIZE,
    TASK_MULTI_UPDATE,
    TASK_TYPE_MATERIAL_DASHBOARD,
  ],
  ids: [
    TASK_COMPACT_DWC,
    TASK_FIELD_SYNCHRONIZE,
    TASK_MULTI_UPDATE,
    TASK_TYPE_MATERIAL_DASHBOARD,
  ],
};
