import {
  TASK_COMPACT_DWC,
  TASK_FIELD_SYNCHRONIZE,
  TASK_MULTI_UPDATE, TASK_TABLE_ANNOTATOR,
} from "../constants/links";

export const AssertedDistribution = {
  all: [TASK_COMPACT_DWC, TASK_FIELD_SYNCHRONIZE, TASK_MULTI_UPDATE, TASK_TABLE_ANNOTATOR],
  ids: [TASK_COMPACT_DWC, TASK_FIELD_SYNCHRONIZE, TASK_MULTI_UPDATE, TASK_TABLE_ANNOTATOR],
};
