import {
  TASK_BIOLOGICAL_ASSOCIATION_EXTENSION,
  TASK_BIOLOGICAL_ASSOCIATION_TABLE,
  TASK_BIOLOGICAL_ASSOCIATION_GLOBI_TABLE,
  TASK_BIOLOGICAL_ASSOCIATION_FAMILY_SUMMARY,
  TASK_BIOLOGICAL_ASSOCIATION_GRAPH,
  TASK_BIOLOGICAL_ASSOCIATION_SUMMARY,
} from '../constants/links'

export const BiologicalAssociation = {
  all: [
    TASK_BIOLOGICAL_ASSOCIATION_EXTENSION,
    TASK_BIOLOGICAL_ASSOCIATION_TABLE,
    TASK_BIOLOGICAL_ASSOCIATION_GLOBI_TABLE,
    TASK_BIOLOGICAL_ASSOCIATION_FAMILY_SUMMARY,
    TASK_BIOLOGICAL_ASSOCIATION_GRAPH,
    TASK_BIOLOGICAL_ASSOCIATION_SUMMARY,
  ],
  ids: [
    TASK_BIOLOGICAL_ASSOCIATION_EXTENSION,
    TASK_BIOLOGICAL_ASSOCIATION_TABLE,
    TASK_BIOLOGICAL_ASSOCIATION_GLOBI_TABLE,
    TASK_BIOLOGICAL_ASSOCIATION_FAMILY_SUMMARY,
    TASK_BIOLOGICAL_ASSOCIATION_GRAPH,
    TASK_BIOLOGICAL_ASSOCIATION_SUMMARY,
  ]
}
