import {
  TASK_BIOLOGICAL_ASSOCIATION_EXTENSION,
  TASK_BIOLOGICAL_ASSOCIATION_TABLE,
  TASK_BIOLOGICAL_ASSOCIATION_GLOBI_TABLE,
  TASK_BIOLOGICAL_ASSOCIATION_FAMILY_SUMMARY,
  TASK_BIOLOGICAL_ASSOCIATION_GRAPH,
  TASK_BIOLOGICAL_ASSOCIATION_SUMMARY,
  TASK_FIELD_SYNCHRONIZE,
  TASK_MULTI_UPDATE, TASK_TABLE_ANNOTATOR
} from '../constants/links'

export const BiologicalAssociation = {
  all: [
    TASK_BIOLOGICAL_ASSOCIATION_EXTENSION,
    TASK_BIOLOGICAL_ASSOCIATION_TABLE,
    TASK_BIOLOGICAL_ASSOCIATION_GLOBI_TABLE,
    TASK_BIOLOGICAL_ASSOCIATION_FAMILY_SUMMARY,
    TASK_BIOLOGICAL_ASSOCIATION_GRAPH,
    TASK_BIOLOGICAL_ASSOCIATION_SUMMARY,
    TASK_FIELD_SYNCHRONIZE,
    TASK_MULTI_UPDATE, TASK_TABLE_ANNOTATOR
  ],
  ids: [
    TASK_BIOLOGICAL_ASSOCIATION_EXTENSION,
    TASK_BIOLOGICAL_ASSOCIATION_TABLE,
    TASK_BIOLOGICAL_ASSOCIATION_GLOBI_TABLE,
    TASK_BIOLOGICAL_ASSOCIATION_FAMILY_SUMMARY,
    TASK_BIOLOGICAL_ASSOCIATION_GRAPH,
    TASK_BIOLOGICAL_ASSOCIATION_SUMMARY,
    TASK_FIELD_SYNCHRONIZE,
    TASK_MULTI_UPDATE, TASK_TABLE_ANNOTATOR
  ]
}
