import {
  TASK_COLLECTION_OBJECT_MATCH,
  TASK_COLLECTION_OBJECT_TABLE,
  TASK_COLLECTION_OBJECT_SUMMARY,
  TASK_COLLECTION_OBJECT_OUTDATED_NAMES,
  TASK_FIELD_SYNCHRONIZE,
  TASK_NEW_CONTAINER,
  TASK_SIMPLEMAPPR,
  TASK_MULTI_UPDATE
} from '../constants/links'

export const CollectionObject = {
  all: [
    TASK_COLLECTION_OBJECT_MATCH,
    TASK_COLLECTION_OBJECT_OUTDATED_NAMES,
    TASK_COLLECTION_OBJECT_SUMMARY,
    TASK_COLLECTION_OBJECT_TABLE,
    TASK_FIELD_SYNCHRONIZE,
    TASK_NEW_CONTAINER,
    TASK_SIMPLEMAPPR,
    TASK_MULTI_UPDATE
  ],
  ids: [
    TASK_COLLECTION_OBJECT_MATCH,
    TASK_COLLECTION_OBJECT_OUTDATED_NAMES,
    TASK_COLLECTION_OBJECT_SUMMARY,
    TASK_COLLECTION_OBJECT_TABLE,
    TASK_FIELD_SYNCHRONIZE,
    TASK_NEW_CONTAINER,
    TASK_SIMPLEMAPPR,
    TASK_MULTI_UPDATE
  ]
}
