import {
  TASK_COLLECTING_EVENT_SPATIAL_SUMMARY,
  TASK_FIELD_SYNCHRONIZE,
  TASK_MULTI_UPDATE,
  TASK_COLLECTING_EVENT_METADATA,
  TASK_PROJECT_VOCABULARY
} from '../constants/links'

export const CollectingEvent = {
  all: [
    TASK_COLLECTING_EVENT_SPATIAL_SUMMARY,
    TASK_FIELD_SYNCHRONIZE,
    TASK_MULTI_UPDATE,
    TASK_COLLECTING_EVENT_METADATA
  ],
  ids: [
    TASK_COLLECTING_EVENT_SPATIAL_SUMMARY,
    TASK_FIELD_SYNCHRONIZE,
    TASK_MULTI_UPDATE,
    TASK_COLLECTING_EVENT_METADATA,
    TASK_PROJECT_VOCABULARY
  ]
}
