import {
  TASK_COLLECTING_EVENT_SPATIAL_SUMMARY,
  TASK_FIELD_SYNCHRONIZE,
  TASK_MULTI_UPDATE
} from '../constants/links'

export const CollectingEvent = {
  all: [
    TASK_COLLECTING_EVENT_SPATIAL_SUMMARY,
    TASK_FIELD_SYNCHRONIZE,
    TASK_MULTI_UPDATE
  ],
  ids: [
    TASK_COLLECTING_EVENT_SPATIAL_SUMMARY,
    TASK_FIELD_SYNCHRONIZE,
    TASK_MULTI_UPDATE
  ]
}
