import {
  TASK_FIELD_SYNCHRONIZE,
  TASK_MULTI_UPDATE, TASK_TABLE_ANNOTATOR,
  TASK_PROJECT_VOCABULARY
} from '../constants/links'

export const Content = {
  all: [TASK_FIELD_SYNCHRONIZE, TASK_MULTI_UPDATE, TASK_TABLE_ANNOTATOR],
  ids: [TASK_FIELD_SYNCHRONIZE, TASK_MULTI_UPDATE, TASK_TABLE_ANNOTATOR, TASK_PROJECT_VOCABULARY]
}
