import {
  TASK_COMPACT_DWC,
  TASK_DWC_OCCURRENCE_STATUS,
  TASK_PROJECT_VOCABULARY,
  TASK_TYPE_MATERIAL_DASHBOARD,
} from "../constants/links";

export const DwcOccurrence = {
  all: [TASK_COMPACT_DWC, TASK_DWC_OCCURRENCE_STATUS, TASK_TYPE_MATERIAL_DASHBOARD],
  ids: [
    TASK_COMPACT_DWC,
    TASK_DWC_OCCURRENCE_STATUS,
    TASK_PROJECT_VOCABULARY,
    TASK_TYPE_MATERIAL_DASHBOARD,
  ],
};
