import { TASK_FIELD_SYNCHRONIZE, TASK_NEW_CONTAINER } from '../constants/links'

export const Extract = {
  all: [TASK_FIELD_SYNCHRONIZE, TASK_NEW_CONTAINER],
  ids: [TASK_FIELD_SYNCHRONIZE, TASK_NEW_CONTAINER]
}
