import {
  TASK_FIELD_SYNCHRONIZE,
  TASK_NEW_CONTAINER,
  TASK_MULTI_UPDATE
} from '../constants/links'

export const Extract = {
  all: [TASK_FIELD_SYNCHRONIZE, TASK_NEW_CONTAINER, TASK_MULTI_UPDATE],
  ids: [TASK_FIELD_SYNCHRONIZE, TASK_NEW_CONTAINER, TASK_MULTI_UPDATE]
}
