import {
  TASK_COMPACT_DWC,
  TASK_DUPLICATE_DATA_ATTRIBUTES,
  TASK_PROJECT_VOCABULARY,
  TASK_MONOGRAPH_FACILITATOR,
  TASK_FIELD_OCCURRENCE_MEDIA_EXTENSION,
  TASK_TABLE_ANNOTATOR,
} from "../constants/links";

export const FieldOccurrence = {
  all: [
    TASK_COMPACT_DWC,
    TASK_DUPLICATE_DATA_ATTRIBUTES,
    TASK_FIELD_OCCURRENCE_MEDIA_EXTENSION,
    TASK_MONOGRAPH_FACILITATOR,
    TASK_TABLE_ANNOTATOR,
  ],
  ids: [
    TASK_COMPACT_DWC,
    TASK_DUPLICATE_DATA_ATTRIBUTES,
    TASK_FIELD_OCCURRENCE_MEDIA_EXTENSION,
    TASK_PROJECT_VOCABULARY,
    TASK_MONOGRAPH_FACILITATOR,
    TASK_TABLE_ANNOTATOR,
  ],
};
