import {
  TASK_PROJECT_VOCABULARY,
  TASK_MONOGRAPH_FACILITATOR,
  TASK_FIELD_OCCURRENCE_MEDIA_EXTENSION
} from '../constants/links'

export const FieldOccurrence = {
  all: [
    TASK_FIELD_OCCURRENCE_MEDIA_EXTENSION,
    TASK_MONOGRAPH_FACILITATOR
  ],
  ids: [
    TASK_FIELD_OCCURRENCE_MEDIA_EXTENSION,
    TASK_PROJECT_VOCABULARY,
    TASK_MONOGRAPH_FACILITATOR
  ]
}
