import {
  TASK_FILTER_IMAGES,
  TASK_FIELD_SYNCHRONIZE,
  TASK_MULTI_UPDATE
} from '../constants/links'

export const Image = {
  all: [TASK_FIELD_SYNCHRONIZE, TASK_MULTI_UPDATE],
  ids: [TASK_FILTER_IMAGES, TASK_FIELD_SYNCHRONIZE, TASK_MULTI_UPDATE]
}
