import {
  TASK_LOANS_DASHBOARD,
  TASK_FIELD_SYNCHRONIZE,
  TASK_MULTI_UPDATE
} from '../constants/links'

export const Loan = {
  all: [TASK_LOANS_DASHBOARD, TASK_FIELD_SYNCHRONIZE, TASK_MULTI_UPDATE],
  ids: [TASK_LOANS_DASHBOARD, TASK_FIELD_SYNCHRONIZE, TASK_MULTI_UPDATE]
}
