import {
  TASK_LOANS_DASHBOARD,
  TASK_FIELD_SYNCHRONIZE
} from '../constants/links'

export const Loan = {
  all: [TASK_LOANS_DASHBOARD, TASK_FIELD_SYNCHRONIZE],
  ids: [TASK_LOANS_DASHBOARD, TASK_FIELD_SYNCHRONIZE]
}
