import {
  TASK_LOANS_DASHBOARD,
  TASK_FIELD_SYNCHRONIZE,
  TASK_MULTI_UPDATE, TASK_TABLE_ANNOTATOR,
  TASK_PROJECT_VOCABULARY
} from '../constants/links'

export const Loan = {
  all: [TASK_LOANS_DASHBOARD, TASK_FIELD_SYNCHRONIZE, TASK_MULTI_UPDATE, TASK_TABLE_ANNOTATOR],
  ids: [
    TASK_LOANS_DASHBOARD,
    TASK_FIELD_SYNCHRONIZE,
    TASK_MULTI_UPDATE, TASK_TABLE_ANNOTATOR,
    TASK_PROJECT_VOCABULARY
  ]
}
