import {
  TASK_CACHED_MAP_ITEM,
  TASK_FIELD_SYNCHRONIZE
} from '../constants/links'

export const Otu = {
  all: [TASK_CACHED_MAP_ITEM, TASK_FIELD_SYNCHRONIZE],
  ids: [TASK_CACHED_MAP_ITEM, TASK_FIELD_SYNCHRONIZE]
}
