import {
  TASK_CACHED_MAP_ITEM,
  TASK_CITE_KEY,
  TASK_DUPLICATE_DATA_ATTRIBUTES,
  TASK_FIELD_SYNCHRONIZE,
  TASK_INTERACTIVE_KEY,
  TASK_IMAGE_MATRIX,
  TASK_MATERIAL_EXAMINED,
  TASK_MULTI_UPDATE,
  TASK_PROJECT_VOCABULARY,
  TASK_MONOGRAPH_FACILITATOR,
} from "../constants/links";

export const Otu = {
  all: [
    TASK_CACHED_MAP_ITEM,
    TASK_CITE_KEY,
    TASK_DUPLICATE_DATA_ATTRIBUTES,
    TASK_FIELD_SYNCHRONIZE,
    TASK_MATERIAL_EXAMINED,
    TASK_MULTI_UPDATE,
    TASK_MONOGRAPH_FACILITATOR,
  ],
  ids: [
    TASK_CACHED_MAP_ITEM,
    TASK_CITE_KEY,
    TASK_DUPLICATE_DATA_ATTRIBUTES,
    TASK_FIELD_SYNCHRONIZE,
    TASK_IMAGE_MATRIX,
    TASK_INTERACTIVE_KEY,
    TASK_MATERIAL_EXAMINED,
    TASK_MULTI_UPDATE,
    TASK_PROJECT_VOCABULARY,
    TASK_MONOGRAPH_FACILITATOR,
  ],
};
