import {
  TASK_CACHED_MAP_ITEM,
  TASK_FIELD_SYNCHRONIZE,
  TASK_IMAGE_MATRIX,
  TASK_MULTI_UPDATE
} from '../constants/links'

export const Otu = {
  all: [TASK_CACHED_MAP_ITEM, TASK_FIELD_SYNCHRONIZE, TASK_MULTI_UPDATE],
  ids: [
    TASK_CACHED_MAP_ITEM,
    TASK_FIELD_SYNCHRONIZE,
    TASK_IMAGE_MATRIX,
    TASK_MULTI_UPDATE
  ]
}
