import {
  TASK_PEOPLE_METADATA,
  TASK_FIELD_SYNCHRONIZE,
  TASK_MULTI_UPDATE
} from '../constants/links'

export const People = {
  all: [TASK_PEOPLE_METADATA, TASK_FIELD_SYNCHRONIZE, TASK_MULTI_UPDATE],
  ids: [TASK_PEOPLE_METADATA, TASK_FIELD_SYNCHRONIZE, TASK_MULTI_UPDATE]
}
