import { TASK_FIELD_SYNCHRONIZE, TASK_MULTI_UPDATE } from '../constants/links'

export const Sound = {
  all: [TASK_FIELD_SYNCHRONIZE, TASK_MULTI_UPDATE],
  ids: [TASK_FIELD_SYNCHRONIZE, TASK_MULTI_UPDATE]
}
