import { TASK_FIELD_SYNCHRONIZE, TASK_MULTI_UPDATE, TASK_TABLE_ANNOTATOR } from '../constants/links'

export const Sound = {
  all: [TASK_FIELD_SYNCHRONIZE, TASK_MULTI_UPDATE, TASK_TABLE_ANNOTATOR],
  ids: [TASK_FIELD_SYNCHRONIZE, TASK_MULTI_UPDATE, TASK_TABLE_ANNOTATOR]
}
