import {
  TASK_SOURCE_CITATION_TOTALS,
  TASK_FIELD_SYNCHRONIZE
} from '../constants/links'

export const Source = {
  all: [TASK_SOURCE_CITATION_TOTALS, TASK_FIELD_SYNCHRONIZE],
  ids: [TASK_SOURCE_CITATION_TOTALS, TASK_FIELD_SYNCHRONIZE]
}
