import {
  TASK_DOCUMENTS_PACKAGER,
  TASK_SOURCE_CITATION_TOTALS,
  TASK_FIELD_SYNCHRONIZE,
  TASK_MULTI_UPDATE, TASK_TABLE_ANNOTATOR,
  TASK_PROJECT_VOCABULARY
} from '../constants/links'

export const Source = {
  all: [TASK_SOURCE_CITATION_TOTALS, TASK_FIELD_SYNCHRONIZE, TASK_MULTI_UPDATE, TASK_TABLE_ANNOTATOR],
  ids: [
    TASK_SOURCE_CITATION_TOTALS,
    TASK_DOCUMENTS_PACKAGER,
    TASK_FIELD_SYNCHRONIZE,
    TASK_MULTI_UPDATE, TASK_TABLE_ANNOTATOR,
    TASK_PROJECT_VOCABULARY
  ]
}
