import {
  TASK_TAXON_NAME_STATS,
  TASK_FIELD_SYNCHRONIZE,
  TASK_MULTI_UPDATE,
  TASK_TAXON_NAME_AUTHOR_SUMMARY,
  TASK_TAXON_NAME_GENDER,
  TASK_TAXON_NAME_RECLASSIFIER
} from '../constants/links'

export const TaxonName = {
  all: [
    TASK_TAXON_NAME_STATS,
    TASK_FIELD_SYNCHRONIZE,
    TASK_MULTI_UPDATE,
    TASK_TAXON_NAME_AUTHOR_SUMMARY,
    TASK_TAXON_NAME_GENDER,
    TASK_TAXON_NAME_RECLASSIFIER
  ],
  ids: [
    TASK_TAXON_NAME_STATS,
    TASK_FIELD_SYNCHRONIZE,
    TASK_MULTI_UPDATE,
    TASK_TAXON_NAME_AUTHOR_SUMMARY,
    TASK_TAXON_NAME_GENDER,
    TASK_TAXON_NAME_RECLASSIFIER
  ]
}
