import {
  TASK_TAXON_NAME_STATS,
  TASK_FIELD_SYNCHRONIZE,
  TASK_MULTI_UPDATE,
  TASK_TAXON_NAME_GENDER,
  TASK_PROJECT_VOCABULARY
} from '../constants/links'

export const TaxonNameRelationship = {
  all: [TASK_TAXON_NAME_STATS, TASK_FIELD_SYNCHRONIZE, TASK_MULTI_UPDATE, TASK_TAXON_NAME_GENDER ],
  ids: [
    TASK_TAXON_NAME_STATS,
    TASK_FIELD_SYNCHRONIZE,
    TASK_MULTI_UPDATE,
    TASK_TAXON_NAME_GENDER,
    TASK_PROJECT_VOCABULARY
  ]
}
