export function makeCollectingEvent (ceData = {}) {
  return {
    id: ceData.id,
    globalId: ceData.global_id,
    printLabel: ceData.print_label,
    printLabelNumberToPrint: ceData.print_label_number_to_print,
    documentLabel: ceData.document_label,
    verbatimLabel: ceData.verbatim_label,
    verbatimLocality: ceData.verbatim_locality,
    verbatimDate: ceData.verbatim_date,
    verbatimLongitude: ceData.verbatim_longitude,
    verbatimLatitude: ceData.verbatim_latitude,
    verbatimGeolocationUncertainty: ceData.verbatim_geolocation_uncertainty,
    verbatimTripIdentifier: ceData.verbatim_trip_identifier,
    verbatimCollectors: ceData.verbatim_collectors,
    verbatimMethod: ceData.verbatim_method,
    verbatimHabitat: ceData.verbatim_habitat,
    verbatimDatum: ceData.verbatim_datum,
    verbatimElevation: ceData.verbatim_elevation,
    geographicAreaId: ceData.geographic_area_id,
    minimumElevation: ceData.minimum_elevation,
    maximumElevation: ceData.maximum_elevation,
    elevationPrecision: ceData.elevation_precision,
    timeStartHour: ceData.time_start_hour,
    timeStartMinute: ceData.time_start_minute,
    timeStartSecond: ceData.time_start_second,
    timeEndHour: ceData.time_end_hour,
    timeEndMinute: ceData.time_end_minute,
    timeEndSecond: ceData.time_end_second,
    startDateDay: ceData.start_date_day,
    startDateMonth: ceData.start_date_month,
    startDateYear: ceData.start_date_year,
    endDateDay: ceData.end_date_day,
    endDateMonth: ceData.end_date_month,
    endDateYear: ceData.end_date_year,
    group: ceData.group,
    member: ceData.member,
    formation: ceData.formation,
    lithology: ceData.lithology,
    maxMa: ceData.max_ma,
    minMa: ceData.min_ma,
    fieldNotes: ceData.field_notes,
    metaPrioritizeGeographicArea: ceData.meta_prioritize_geographic_area,
    rolesAttributes: ceData.role_attributes || [],
    identifiersAttributes: ceData.identifiers_attributes || []
  }
}
