json.extract! document, :id, 
  :document_file_file_name,
  :document_file_content_type,
  :document_file_file_size,
  :document_file_updated_at,
  :page_map,
  :page_total,
  :is_public,
  :document_file_fingerprint,
  :document_file, :created_by_id, :updated_by_id, :created_at, :updated_at
