export default {
    NONE: '',
    GEOGRAPHICAL_AREA_DATA_ORIGIN_COUNTRY_NAMES_AND_CODE_ELEMENTS: 'country_names_and_code_elements',
    GEOGRAPHICAL_AREA_DATA_ORIGIN_GADM: 'gadm',
    GEOGRAPHICAL_AREA_DATA_ORIGIN_NE: 'ne',
    GEOGRAPHICAL_AREA_DATA_ORIGIN_SFG: 'SFG',
    GEOGRAPHICAL_AREA_DATA_ORIGIN_TDWG: 'tdwg'
}
