export default {
    NONE: '',
    GEOGRAPHICAL_AREA_DATA_ORIGIN_GADM: 'gadm',
    GEOGRAPHICAL_AREA_DATA_ORIGIN_SFG: 'SFG',
    GEOGRAPHICAL_AREA_DATA_ORIGIN_NE_STATES: 'ne_states',
    GEOGRAPHICAL_AREA_DATA_ORIGIN_COUNTRY_NAMES_AND_CODE_ELEMENTS: 'country_names_and_code_elements',
    GEOGRAPHICAL_AREA_DATA_ORIGIN_NE_COUNTRIES: 'ne_countries',
    GEOGRAPHICAL_AREA_DATA_ORIGIN_TDWG_L1: 'tdwg_l1',
    GEOGRAPHICAL_AREA_DATA_ORIGIN_TDWG_L2: 'tdwg_l2',
    GEOGRAPHICAL_AREA_DATA_ORIGIN_TDWG_L3: 'tdwg_l3',
    GEOGRAPHICAL_AREA_DATA_ORIGIN_TDWG_L4: 'tdwg_l4'
}
