export const COMBINATION = 'Combination'
export const CONTAINER = 'Container'
export const IMAGE = 'Image'
export const TAXON_NAME = 'TaxonName'
export const COLLECTION_OBJECT = 'CollectionObject'
export const COLLECTING_EVENT = 'CollectingEvent'
export const TYPE_MATERIAL = 'TypeMaterial'
export const OTU = 'Otu'
