export const OBSERVATION_MATRIX_ROW_DYNAMIC_TAG = 'ObservationMatrixRowItem::Dynamic::Tag'
export const OBSERVATION_MATRIX_ROW_DYNAMIC_TAXONNAME = 'ObservationMatrixRowItem::Dynamic::TaxonName'
export const OBSERVATION_MATRIX_ROW_SINGLE = 'ObservationMatrixRowItem::Single'
export const OBSERVATION_MATRIX_ROW_SINGLE_OTU = 'ObservationMatrixRowItem::Single::Otu'
export const OBSERVATION_MATRIX_ROW_SINGLE_COLLECTION_OBJECT = 'ObservationMatrixRowItem::Single::CollectionObject'
