export const ROLE_COLLECTOR = 'Collector'
export const ROLE_DETERMINER = 'Determiner'
export const ROLE_SOURCE_EDITOR = 'SourceEditor'
export const ROLE_TAXON_NAME_AUTHOR = 'TaxonNameAuthor'
export const ROLE_LOAN_RECIPIENT = 'LoanRecipient'
export const ROLE_LOAN_SUPERVISOR = 'LoanSupervisor'
