class AddHousekeepingFields < ActiveRecord::Migration
  def change
    add_column :taxon_name_relationships, :created_by_id, :integer, index: true
    add_column :taxon_name_relationships, :updated_by_id, :integer, index: true
    add_column :taxon_name_relationships, :project_id, :integer, index: true
    add_column :projects, :created_by_id, :integer, index: true
    add_column :projects, :updated_by_id, :integer, index: true
    add_column :projects, :project_id, :integer, index: true
    add_column :attributes, :created_by_id, :integer, index: true
    add_column :attributes, :updated_by_id, :integer, index: true
    add_column :attributes, :project_id, :integer, index: true
    add_column :collecting_events, :created_by_id, :integer, index: true
    add_column :collecting_events, :updated_by_id, :integer, index: true
    add_column :collecting_events, :project_id, :integer, index: true
    add_column :taxon_names, :created_by_id, :integer, index: true
    add_column :taxon_names, :updated_by_id, :integer, index: true
    add_column :taxon_names, :project_id, :integer, index: true
    add_column :otus, :created_by_id, :integer, index: true
    add_column :otus, :updated_by_id, :integer, index: true
    add_column :otus, :project_id, :integer, index: true
    add_column :people, :created_by_id, :integer, index: true
    add_column :people, :updated_by_id, :integer, index: true
    add_column :roles, :created_by_id, :integer, index: true
    add_column :roles, :updated_by_id, :integer, index: true
    add_column :roles, :project_id, :integer, index: true
    add_column :collection_objects, :created_by_id, :integer, index: true
    add_column :collection_objects, :updated_by_id, :integer, index: true
    add_column :collection_objects, :project_id, :integer, index: true
    add_column :alternate_values, :created_by_id, :integer, index: true
    add_column :alternate_values, :updated_by_id, :integer, index: true
    add_column :biocuration_classes, :created_by_id, :integer, index: true
    add_column :biocuration_classes, :updated_by_id, :integer, index: true
    add_column :biocuration_classes, :project_id, :integer, index: true
    add_column :biocuration_classifications, :created_by_id, :integer, index: true
    add_column :biocuration_classifications, :updated_by_id, :integer, index: true
    add_column :biocuration_classifications, :project_id, :integer, index: true
    add_column :biological_associations, :created_by_id, :integer, index: true
    add_column :biological_associations, :updated_by_id, :integer, index: true
    add_column :biological_associations, :project_id, :integer, index: true
    add_column :biological_associations_graphs, :created_by_id, :integer, index: true
    add_column :biological_associations_graphs, :updated_by_id, :integer, index: true
    add_column :biological_associations_graphs, :project_id, :integer, index: true
    add_column :biological_properties, :created_by_id, :integer, index: true
    add_column :biological_properties, :updated_by_id, :integer, index: true
    add_column :biological_properties, :project_id, :integer, index: true
    add_column :biological_relationships, :created_by_id, :integer, index: true
    add_column :biological_relationships, :updated_by_id, :integer, index: true
    add_column :biological_relationships, :project_id, :integer, index: true
    add_column :biological_relationship_properties, :created_by_id, :integer, index: true
    add_column :biological_relationship_properties, :updated_by_id, :integer, index: true
    add_column :biological_relationship_properties, :project_id, :integer, index: true
    add_column :citations, :created_by_id, :integer, index: true
    add_column :citations, :updated_by_id, :integer, index: true
    add_column :citations, :project_id, :integer, index: true
    add_column :citation_topics, :created_by_id, :integer, index: true
    add_column :citation_topics, :updated_by_id, :integer, index: true
    add_column :citation_topics, :project_id, :integer, index: true
    add_column :containers, :created_by_id, :integer, index: true
    add_column :containers, :updated_by_id, :integer, index: true
    add_column :containers, :project_id, :integer, index: true
    add_column :container_items, :created_by_id, :integer, index: true
    add_column :container_items, :updated_by_id, :integer, index: true
    add_column :container_items, :project_id, :integer, index: true
    add_column :contents, :created_by_id, :integer, index: true
    add_column :contents, :updated_by_id, :integer, index: true
    add_column :contents, :project_id, :integer, index: true
    add_column :controlled_vocabulary_terms, :created_by_id, :integer, index: true
    add_column :controlled_vocabulary_terms, :updated_by_id, :integer, index: true
    add_column :controlled_vocabulary_terms, :project_id, :integer, index: true
    add_column :identifiers, :created_by_id, :integer, index: true
    add_column :identifiers, :updated_by_id, :integer, index: true
    add_column :languages, :created_by_id, :integer, index: true
    add_column :languages, :updated_by_id, :integer, index: true
    add_column :namespaces, :created_by_id, :integer, index: true
    add_column :namespaces, :updated_by_id, :integer, index: true
    add_column :notes, :created_by_id, :integer, index: true
    add_column :notes, :updated_by_id, :integer, index: true
    add_column :notes, :project_id, :integer, index: true
    add_column :preparation_types, :created_by_id, :integer, index: true
    add_column :preparation_types, :updated_by_id, :integer, index: true
    add_column :project_members, :created_by_id, :integer, index: true
    add_column :project_members, :updated_by_id, :integer, index: true
    add_column :ranged_lot_categories, :created_by_id, :integer, index: true
    add_column :ranged_lot_categories, :updated_by_id, :integer, index: true
    add_column :ranged_lot_categories, :project_id, :integer, index: true
    add_column :repositories, :created_by_id, :integer, index: true
    add_column :repositories, :updated_by_id, :integer, index: true
    add_column :sources, :created_by_id, :integer, index: true
    add_column :sources, :updated_by_id, :integer, index: true
    add_column :tags, :created_by_id, :integer, index: true
    add_column :tags, :updated_by_id, :integer, index: true
    add_column :tags, :project_id, :integer, index: true
    add_column :taxon_determinations, :created_by_id, :integer, index: true
    add_column :taxon_determinations, :updated_by_id, :integer, index: true
    add_column :taxon_determinations, :project_id, :integer, index: true
    add_column :taxon_name_classifications, :created_by_id, :integer, index: true
    add_column :taxon_name_classifications, :updated_by_id, :integer, index: true
    add_column :taxon_name_classifications, :project_id, :integer, index: true
    add_column :type_specimens, :created_by_id, :integer, index: true
    add_column :type_specimens, :updated_by_id, :integer, index: true
    add_column :type_specimens, :project_id, :integer, index: true
    add_column :users, :created_by_id, :integer, index: true
    add_column :users, :updated_by_id, :integer, index: true
  end
end
