require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe AlternateValuesController, :type => :controller do
  before(:each) {
    sign_in
  }

  # This should return the minimal set of attributes required to create a valid
  # AlternateValue. As you add validations to AlternateValue, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { strip_housekeeping_attributes( FactoryGirl.build(:valid_alternate_value).attributes) }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # AlternateValuesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all alternate_values as @alternate_values" do
      alternate_value = AlternateValue.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:alternate_values)).to eq([alternate_value])
    end
  end

  describe "GET show" do
    it "assigns the requested alternate_value as @alternate_value" do
      alternate_value = AlternateValue.create! valid_attributes
      get :show, {:id => alternate_value.to_param}, valid_session
      expect(assigns(:alternate_value)).to eq(alternate_value)
    end
  end

  describe "GET new" do
    it "assigns a new alternate_value as @alternate_value" do
      get :new, {}, valid_session
      expect(assigns(:alternate_value)).to be_a_new(AlternateValue)
    end
  end

  describe "GET edit" do
    it "assigns the requested alternate_value as @alternate_value" do
      alternate_value = AlternateValue.create! valid_attributes
      get :edit, {:id => alternate_value.to_param}, valid_session
      expect(assigns(:alternate_value)).to eq(alternate_value)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new AlternateValue" do
        expect {
          post :create, {:alternate_value => valid_attributes}, valid_session
        }.to change(AlternateValue, :count).by(1)
      end

      it "assigns a newly created alternate_value as @alternate_value" do
        post :create, {:alternate_value => valid_attributes}, valid_session
        expect(assigns(:alternate_value)).to be_a(AlternateValue)
        expect(assigns(:alternate_value)).to be_persisted
      end

      it "redirects to the created alternate_value" do
        post :create, {:alternate_value => valid_attributes}, valid_session
        expect(response).to redirect_to(AlternateValue.last.becomes(AlternateValue))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved alternate_value as @alternate_value" do
        # Trigger the behavior that occurs when invalid params are submitted
        allow_any_instance_of(AlternateValue).to receive(:save).and_return(false)
        post :create, {:alternate_value => {value: 'Bar'  }}, valid_session
        expect(assigns(:alternate_value)).to be_a_new(AlternateValue)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        allow_any_instance_of(AlternateValue).to receive(:save).and_return(false)
        post :create, {:alternate_value => {value: 'Foo'  }}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested alternate_value" do
        alternate_value = AlternateValue.create! valid_attributes
        # Assuming there are no other alternate_values in the database, this
        # specifies that the AlternateValue created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        expect_any_instance_of(AlternateValue).to receive(:update).with({ 'value' => 'Smorf' })
        put :update, {:id => alternate_value.to_param, :alternate_value => { value: 'Smorf' }}, valid_session
      end

      it "assigns the requested alternate_value as @alternate_value" do
        alternate_value = AlternateValue.create! valid_attributes
        put :update, {:id => alternate_value.to_param, :alternate_value => valid_attributes}, valid_session
        expect(assigns(:alternate_value)).to eq(alternate_value)
      end

      it "redirects to the alternate_value" do
        alternate_value = AlternateValue.create! valid_attributes
        put :update, {:id => alternate_value.to_param, :alternate_value => valid_attributes}, valid_session
        expect(response).to redirect_to(alternate_value.becomes(AlternateValue))
      end
    end

    describe "with invalid params" do
      it "assigns the alternate_value as @alternate_value" do
        alternate_value = AlternateValue.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        allow_any_instance_of(AlternateValue).to receive(:save).and_return(false)
        put :update, {:id => alternate_value.to_param, :alternate_value => { foo: 'Bar'  }}, valid_session
        expect(assigns(:alternate_value)).to eq(alternate_value)
      end

      it "re-renders the 'edit' template" do
        alternate_value = AlternateValue.create!(valid_attributes)
        # Trigger the behavior that occurs when invalid params are submitted
        allow_any_instance_of(AlternateValue).to receive(:save).and_return(false)
        put :update, {:id => alternate_value.to_param, :alternate_value => { value: "Smorf"  }}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested alternate_value" do
      alternate_value = AlternateValue.create! valid_attributes
      expect {
        delete :destroy, {:id => alternate_value.to_param}, valid_session
      }.to change(AlternateValue, :count).by(-1)
    end

    it "redirects to the alternate_values list" do
      alternate_value = AlternateValue.create! valid_attributes
      delete :destroy, {:id => alternate_value.to_param}, valid_session
      expect(response).to redirect_to(alternate_values_url)
    end
  end

end
