require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CitationTopicsController do

  # This should return the minimal set of attributes required to create a valid
  # CitationTopic. As you add validations to CitationTopic, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { {  } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CitationTopicsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all citation_topics as @citation_topics" do
      citation_topic = CitationTopic.create! valid_attributes
      get :index, {}, valid_session
      assigns(:citation_topics).should eq([citation_topic])
    end
  end

  describe "GET show" do
    it "assigns the requested citation_topic as @citation_topic" do
      citation_topic = CitationTopic.create! valid_attributes
      get :show, {:id => citation_topic.to_param}, valid_session
      assigns(:citation_topic).should eq(citation_topic)
    end
  end

  describe "GET new" do
    it "assigns a new citation_topic as @citation_topic" do
      get :new, {}, valid_session
      assigns(:citation_topic).should be_a_new(CitationTopic)
    end
  end

  describe "GET edit" do
    it "assigns the requested citation_topic as @citation_topic" do
      citation_topic = CitationTopic.create! valid_attributes
      get :edit, {:id => citation_topic.to_param}, valid_session
      assigns(:citation_topic).should eq(citation_topic)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new CitationTopic" do
        expect {
          post :create, {:citation_topic => valid_attributes}, valid_session
        }.to change(CitationTopic, :count).by(1)
      end

      it "assigns a newly created citation_topic as @citation_topic" do
        post :create, {:citation_topic => valid_attributes}, valid_session
        assigns(:citation_topic).should be_a(CitationTopic)
        assigns(:citation_topic).should be_persisted
      end

      it "redirects to the created citation_topic" do
        post :create, {:citation_topic => valid_attributes}, valid_session
        response.should redirect_to(CitationTopic.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved citation_topic as @citation_topic" do
        # Trigger the behavior that occurs when invalid params are submitted
        CitationTopic.any_instance.stub(:save).and_return(false)
        post :create, {:citation_topic => {  }}, valid_session
        assigns(:citation_topic).should be_a_new(CitationTopic)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        CitationTopic.any_instance.stub(:save).and_return(false)
        post :create, {:citation_topic => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested citation_topic" do
        citation_topic = CitationTopic.create! valid_attributes
        # Assuming there are no other citation_topics in the database, this
        # specifies that the CitationTopic created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        CitationTopic.any_instance.should_receive(:update).with({ "these" => "params" })
        put :update, {:id => citation_topic.to_param, :citation_topic => { "these" => "params" }}, valid_session
      end

      it "assigns the requested citation_topic as @citation_topic" do
        citation_topic = CitationTopic.create! valid_attributes
        put :update, {:id => citation_topic.to_param, :citation_topic => valid_attributes}, valid_session
        assigns(:citation_topic).should eq(citation_topic)
      end

      it "redirects to the citation_topic" do
        citation_topic = CitationTopic.create! valid_attributes
        put :update, {:id => citation_topic.to_param, :citation_topic => valid_attributes}, valid_session
        response.should redirect_to(citation_topic)
      end
    end

    describe "with invalid params" do
      it "assigns the citation_topic as @citation_topic" do
        citation_topic = CitationTopic.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CitationTopic.any_instance.stub(:save).and_return(false)
        put :update, {:id => citation_topic.to_param, :citation_topic => {  }}, valid_session
        assigns(:citation_topic).should eq(citation_topic)
      end

      it "re-renders the 'edit' template" do
        citation_topic = CitationTopic.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CitationTopic.any_instance.stub(:save).and_return(false)
        put :update, {:id => citation_topic.to_param, :citation_topic => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested citation_topic" do
      citation_topic = CitationTopic.create! valid_attributes
      expect {
        delete :destroy, {:id => citation_topic.to_param}, valid_session
      }.to change(CitationTopic, :count).by(-1)
    end

    it "redirects to the citation_topics list" do
      citation_topic = CitationTopic.create! valid_attributes
      delete :destroy, {:id => citation_topic.to_param}, valid_session
      response.should redirect_to(citation_topics_url)
    end
  end

end
