require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CollectingEventsController do
  before(:each) {
   sign_in 
  }

  # This should return the minimal set of attributes required to create a valid
  # Georeference. As you add validations to Georeference be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { 
    strip_housekeeping_attributes( FactoryGirl.build(:valid_collecting_event).attributes )
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CollectingEventsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all collecting_events as @collecting_events" do
      collecting_event = CollectingEvent.create! valid_attributes
      get :index, {}, valid_session
      assigns(:collecting_events).should eq([collecting_event])
    end
  end

  describe "GET show" do
    it "assigns the requested collecting_event as @collecting_event" do
      collecting_event = CollectingEvent.create! valid_attributes
      get :show, {:id => collecting_event.to_param}, valid_session
      assigns(:collecting_event).should eq(collecting_event)
    end
  end

  describe "GET new" do
    it "assigns a new collecting_event as @collecting_event" do
      get :new, {}, valid_session
      assigns(:collecting_event).should be_a_new(CollectingEvent)
    end
  end

  describe "GET edit" do
    it "assigns the requested collecting_event as @collecting_event" do
      collecting_event = CollectingEvent.create! valid_attributes
      get :edit, {:id => collecting_event.to_param}, valid_session
      assigns(:collecting_event).should eq(collecting_event)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new CollectingEvent" do
        expect {
          post :create, {:collecting_event => valid_attributes}, valid_session
        }.to change(CollectingEvent, :count).by(1)
      end

      it "assigns a newly created collecting_event as @collecting_event" do
        post :create, {:collecting_event => valid_attributes}, valid_session
        assigns(:collecting_event).should be_a(CollectingEvent)
        assigns(:collecting_event).should be_persisted
      end

      it "redirects to the created collecting_event" do
        post :create, {:collecting_event => valid_attributes}, valid_session
        response.should redirect_to(CollectingEvent.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved collecting_event as @collecting_event" do
        # Trigger the behavior that occurs when invalid params are submitted
        CollectingEvent.any_instance.stub(:save).and_return(false)
        post :create, {:collecting_event => { "verbatim_label" => "invalid value" }}, valid_session
        assigns(:collecting_event).should be_a_new(CollectingEvent)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        CollectingEvent.any_instance.stub(:save).and_return(false)
        post :create, {:collecting_event => { "verbatim_label" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested collecting_event" do
        collecting_event = CollectingEvent.create! valid_attributes
        # Assuming there are no other collecting_events in the database, this
        # specifies that the CollectingEvent created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        CollectingEvent.any_instance.should_receive(:update).with({ "verbatim_label" => "MyText" })
        put :update, {:id => collecting_event.to_param, :collecting_event => { "verbatim_label" => "MyText" }}, valid_session
      end

      it "assigns the requested collecting_event as @collecting_event" do
        collecting_event = CollectingEvent.create! valid_attributes
        put :update, {:id => collecting_event.to_param, :collecting_event => valid_attributes}, valid_session
        assigns(:collecting_event).should eq(collecting_event)
      end

      it "redirects to the collecting_event" do
        collecting_event = CollectingEvent.create! valid_attributes
        put :update, {:id => collecting_event.to_param, :collecting_event => valid_attributes}, valid_session
        response.should redirect_to(collecting_event)
      end
    end

    describe "with invalid params" do
      it "assigns the collecting_event as @collecting_event" do
        collecting_event = CollectingEvent.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CollectingEvent.any_instance.stub(:save).and_return(false)
        put :update, {:id => collecting_event.to_param, :collecting_event => { "verbatim_label" => "invalid value" }}, valid_session
        assigns(:collecting_event).should eq(collecting_event)
      end

      it "re-renders the 'edit' template" do
        collecting_event = CollectingEvent.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CollectingEvent.any_instance.stub(:save).and_return(false)
        put :update, {:id => collecting_event.to_param, :collecting_event => { "verbatim_label" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested collecting_event" do
      collecting_event = CollectingEvent.create! valid_attributes
      expect {
        delete :destroy, {:id => collecting_event.to_param}, valid_session
      }.to change(CollectingEvent, :count).by(-1)
    end

    it "redirects to the collecting_events list" do
      collecting_event = CollectingEvent.create! valid_attributes
      delete :destroy, {:id => collecting_event.to_param}, valid_session
      response.should redirect_to(collecting_events_url)
    end
  end

end
