require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ControlledVocabularyTermsController do

  # This should return the minimal set of attributes required to create a valid
  # ControlledVocabularyTerm. As you add validations to ControlledVocabularyTerm, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "type" => "" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ControlledVocabularyTermsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all controlled_vocabulary_terms as @controlled_vocabulary_terms" do
      controlled_vocabulary_term = ControlledVocabularyTerm.create! valid_attributes
      get :index, {}, valid_session
      assigns(:controlled_vocabulary_terms).should eq([controlled_vocabulary_term])
    end
  end

  describe "GET show" do
    it "assigns the requested controlled_vocabulary_term as @controlled_vocabulary_term" do
      controlled_vocabulary_term = ControlledVocabularyTerm.create! valid_attributes
      get :show, {:id => controlled_vocabulary_term.to_param}, valid_session
      assigns(:controlled_vocabulary_term).should eq(controlled_vocabulary_term)
    end
  end

  describe "GET new" do
    it "assigns a new controlled_vocabulary_term as @controlled_vocabulary_term" do
      get :new, {}, valid_session
      assigns(:controlled_vocabulary_term).should be_a_new(ControlledVocabularyTerm)
    end
  end

  describe "GET edit" do
    it "assigns the requested controlled_vocabulary_term as @controlled_vocabulary_term" do
      controlled_vocabulary_term = ControlledVocabularyTerm.create! valid_attributes
      get :edit, {:id => controlled_vocabulary_term.to_param}, valid_session
      assigns(:controlled_vocabulary_term).should eq(controlled_vocabulary_term)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ControlledVocabularyTerm" do
        expect {
          post :create, {:controlled_vocabulary_term => valid_attributes}, valid_session
        }.to change(ControlledVocabularyTerm, :count).by(1)
      end

      it "assigns a newly created controlled_vocabulary_term as @controlled_vocabulary_term" do
        post :create, {:controlled_vocabulary_term => valid_attributes}, valid_session
        assigns(:controlled_vocabulary_term).should be_a(ControlledVocabularyTerm)
        assigns(:controlled_vocabulary_term).should be_persisted
      end

      it "redirects to the created controlled_vocabulary_term" do
        post :create, {:controlled_vocabulary_term => valid_attributes}, valid_session
        response.should redirect_to(ControlledVocabularyTerm.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved controlled_vocabulary_term as @controlled_vocabulary_term" do
        # Trigger the behavior that occurs when invalid params are submitted
        ControlledVocabularyTerm.any_instance.stub(:save).and_return(false)
        post :create, {:controlled_vocabulary_term => { "type" => "invalid value" }}, valid_session
        assigns(:controlled_vocabulary_term).should be_a_new(ControlledVocabularyTerm)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ControlledVocabularyTerm.any_instance.stub(:save).and_return(false)
        post :create, {:controlled_vocabulary_term => { "type" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested controlled_vocabulary_term" do
        controlled_vocabulary_term = ControlledVocabularyTerm.create! valid_attributes
        # Assuming there are no other controlled_vocabulary_terms in the database, this
        # specifies that the ControlledVocabularyTerm created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ControlledVocabularyTerm.any_instance.should_receive(:update).with({ "type" => "" })
        put :update, {:id => controlled_vocabulary_term.to_param, :controlled_vocabulary_term => { "type" => "" }}, valid_session
      end

      it "assigns the requested controlled_vocabulary_term as @controlled_vocabulary_term" do
        controlled_vocabulary_term = ControlledVocabularyTerm.create! valid_attributes
        put :update, {:id => controlled_vocabulary_term.to_param, :controlled_vocabulary_term => valid_attributes}, valid_session
        assigns(:controlled_vocabulary_term).should eq(controlled_vocabulary_term)
      end

      it "redirects to the controlled_vocabulary_term" do
        controlled_vocabulary_term = ControlledVocabularyTerm.create! valid_attributes
        put :update, {:id => controlled_vocabulary_term.to_param, :controlled_vocabulary_term => valid_attributes}, valid_session
        response.should redirect_to(controlled_vocabulary_term)
      end
    end

    describe "with invalid params" do
      it "assigns the controlled_vocabulary_term as @controlled_vocabulary_term" do
        controlled_vocabulary_term = ControlledVocabularyTerm.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ControlledVocabularyTerm.any_instance.stub(:save).and_return(false)
        put :update, {:id => controlled_vocabulary_term.to_param, :controlled_vocabulary_term => { "type" => "invalid value" }}, valid_session
        assigns(:controlled_vocabulary_term).should eq(controlled_vocabulary_term)
      end

      it "re-renders the 'edit' template" do
        controlled_vocabulary_term = ControlledVocabularyTerm.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ControlledVocabularyTerm.any_instance.stub(:save).and_return(false)
        put :update, {:id => controlled_vocabulary_term.to_param, :controlled_vocabulary_term => { "type" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested controlled_vocabulary_term" do
      controlled_vocabulary_term = ControlledVocabularyTerm.create! valid_attributes
      expect {
        delete :destroy, {:id => controlled_vocabulary_term.to_param}, valid_session
      }.to change(ControlledVocabularyTerm, :count).by(-1)
    end

    it "redirects to the controlled_vocabulary_terms list" do
      controlled_vocabulary_term = ControlledVocabularyTerm.create! valid_attributes
      delete :destroy, {:id => controlled_vocabulary_term.to_param}, valid_session
      response.should redirect_to(controlled_vocabulary_terms_url)
    end
  end

end
