require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ContainersController, :type => :controller do
before(:each) {
  sign_in
}

# This should return the minimal set of attributes required to create a valid
  # AlternateValue. As you add validations to AlternateValue, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { strip_housekeeping_attributes(FactoryGirl.build(:valid_container).attributes) }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ContainersController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  before {
    request.env['HTTP_REFERER'] = list_otus_path # logical example
  }

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Container" do
        expect {
          post :create, {:container => valid_attributes}, valid_session
        }.to change(Container, :count).by(1)
      end

      it "assigns a newly created container as @container" do
        post :create, {:container => valid_attributes}, valid_session
        expect(assigns(:container)).to be_a(Container)
        expect(assigns(:container)).to be_persisted
      end

      it "redirects to :back" do
        post :create, {:container => valid_attributes}, valid_session
        expect(response).to redirect_to(list_otus_path)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved container as @container" do
        # Trigger the behavior that occurs when invalid params are submitted
        # Container.any_instance.stub(:save).and_return(false)
        # post :create, {:container => { "name" => "invalid value" }}, valid_session
        # assigns(:container).should be_a_new(Container)
        allow_any_instance_of(Container).to receive(:save).and_return(false)
        post :create, {:container => {:invalid => 'params'}}, valid_session
        expect(assigns(:container)).to be_a_new(Container)
      end

      it "re-renders the :back template" do
        # Trigger the behavior that occurs when invalid params are submitted
        # Container.any_instance.stub(:save).and_return(false)
        # post :create, {:container => { "name" => "invalid value" }}, valid_session
        # response.should redirect_to(list_otus_path)
        allow_any_instance_of(Container).to receive(:save).and_return(false)
        post :create, {:container => {:invalid => 'params'}}, valid_session
        expect(response).to redirect_to(list_otus_path)
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested container" do
        container = Container.create! valid_attributes
        # Assuming there are no other containers in the database, this
        # specifies that the Container created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        # Container.any_instance.should_receive(:update).with({ "name" => "1" })
        # put :update, {:id => container.to_param, :container => { "name" => "1" }}, valid_session
        # todo @mjy Why don't next two lines work with "value" instead of "name"? AlternateValues (random example) uses 'value' => 'Smorf' for first expect, then value: 'Smorf' for second. Those fail here but name seems to work???
        expect_any_instance_of(Container).to receive(:update).with({"name" => 'Smorf'})
        put :update, {:id => container.to_param, :container => {"name" => 'Smorf'}}, valid_session
      end

      it "assigns the requested container as @container" do
        container = Container.create! valid_attributes
        put :update, {:id => container.to_param, :container => valid_attributes}, valid_session
        # assigns(:container).should eq(container)
        expect(assigns(:container)).to eq(container)
      end

      it "redirects to :back" do
        container = Container.create! valid_attributes
        put :update, {:id => container.to_param, :container => valid_attributes}, valid_session
        # response.should redirect_to(list_otus_path)
        expect(response).to redirect_to(list_otus_path)
      end
    end

    describe "with invalid params" do
      it "assigns the container as @container" do
        container = Container.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        # Container.any_instance.stub(:save).and_return(false)
        # put :update, {:id => container.to_param, :container => { "name" => "invalid value" }}, valid_session
        # assigns(:container).should eq(container)
        allow_any_instance_of(Container).to receive(:save).and_return(false)
        put :update, {:id => container.to_param, :container => {:invalid => 'parms'}}, valid_session
        expect(assigns(:container)).to eq(container)
      end

      it "re-renders the :back template" do
        container = Container.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        # Container.any_instance.stub(:save).and_return(false)
        # put :update, {:id => container.to_param, :container => { "name" => "invalid value" }}, valid_session
        # response.should redirect_to(list_otus_path)
        allow_any_instance_of(Container).to receive(:save).and_return(false)
        put :update, {:id => container.to_param, :container => {:invalid => 'parms'}}, valid_session
        expect(response).to redirect_to(list_otus_path)
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested container" do
      container = Container.create! valid_attributes
      expect {
        delete :destroy, {:id => container.to_param}, valid_session
      }.to change(Container, :count).by(-1)
    end

    it "redirects to :back" do
      container = Container.create! valid_attributes
      delete :destroy, {:id => container.to_param}, valid_session
      expect(response).to redirect_to(list_otus_path)
    end
  end

end
