require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe MatrixRowsController, type: :controller do
  before(:each) {
    sign_in
  }

  # This should return the minimal set of attributes required to create a valid
  # MatrixRow. As you add validations to MatrixRow, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    strip_housekeeping_attributes(FactoryGirl.build(:valid_matrix_row).attributes)
  }

  let(:invalid_attributes) {
    {matrix_id: nil, otu_id: nil, collection_object_id: nil}
    # TODO: Create actual/more invalid_attributes
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # MatrixRowsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all matrix_rows as @recent_objects" do
      matrix_row = MatrixRow.create! valid_attributes
      get :index, {}, session: valid_session
      expect(assigns(:recent_objects)).to eq([matrix_row])
    end
  end

  describe "GET #show" do
    it "assigns the requested matrix_row as @matrix_row" do
      matrix_row = MatrixRow.create! valid_attributes
      get :show, {id: matrix_row.to_param}, session: valid_session
      expect(assigns(:matrix_row)).to eq(matrix_row)
    end
  end

  describe "GET #new" do
    it "assigns a new matrix_row as @matrix_row" do
      get :new, {}, session: valid_session
      expect(assigns(:matrix_row)).to be_a_new(MatrixRow)
    end
  end

  describe "GET #edit" do
    it "assigns the requested matrix_row as @matrix_row" do
      matrix_row = MatrixRow.create! valid_attributes
      get :edit, {id: matrix_row.to_param}, session: valid_session
      expect(assigns(:matrix_row)).to eq(matrix_row)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new MatrixRow" do
        expect {
          post :create, {matrix_row: valid_attributes}, session: valid_session
        }.to change(MatrixRow, :count).by(1)
      end

      it "assigns a newly created matrix_row as @matrix_row" do
        post :create, {matrix_row: valid_attributes}, session: valid_session
        expect(assigns(:matrix_row)).to be_a(MatrixRow)
        expect(assigns(:matrix_row)).to be_persisted
      end

      it "redirects to the created matrix_row" do
        post :create, {matrix_row: valid_attributes}, session: valid_session
        expect(response).to redirect_to(MatrixRow.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved matrix_row as @matrix_row" do
        post :create, {matrix_row: invalid_attributes}, session: valid_session
        expect(assigns(:matrix_row)).to be_a_new(MatrixRow)
      end

      it "re-renders the 'new' template" do
        post :create, {matrix_row: invalid_attributes}, session: valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:valid_otu_id) do
        FactoryGirl.create(:valid_otu).id
      end

      let(:new_attributes) {
        #valid_attributes
        attributes = valid_attributes
        attributes[:otu_id] = valid_otu_id
        attributes
        #skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested matrix_row" do
        matrix_row = MatrixRow.create! valid_attributes
        put :update, {id: matrix_row.to_param, matrix_row: new_attributes}, session: valid_session
        matrix_row.reload

        expect(matrix_row.otu_id == valid_otu_id)
        #skip("Add assertions for updated state")
      end

      it "assigns the requested matrix_row as @matrix_row" do
        matrix_row = MatrixRow.create! valid_attributes
        put :update, {id: matrix_row.to_param, matrix_row: valid_attributes}, session: valid_session
        expect(assigns(:matrix_row)).to eq(matrix_row)
      end

      it "redirects to the matrix_row" do
        matrix_row = MatrixRow.create! valid_attributes
        put :update, {id: matrix_row.to_param, matrix_row: valid_attributes}, session: valid_session
        expect(response).to redirect_to(matrix_row)
      end
    end

    context "with invalid params" do
      it "assigns the matrix_row as @matrix_row" do
        matrix_row = MatrixRow.create! valid_attributes
        put :update, {id: matrix_row.to_param, matrix_row: invalid_attributes}, session: valid_session
        expect(assigns(:matrix_row)).to eq(matrix_row)
      end

      it "re-renders the 'edit' template" do
        matrix_row = MatrixRow.create! valid_attributes
        put :update, {id: matrix_row.to_param, matrix_row: invalid_attributes}, session: valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested matrix_row" do
      matrix_row = MatrixRow.create! valid_attributes
      expect {
        delete :destroy, {id: matrix_row.to_param}, session: valid_session
      }.to change(MatrixRow, :count).by(-1)
    end

    it "redirects to the matrix_rows list" do
      matrix_row = MatrixRow.create! valid_attributes
      delete :destroy, {id: matrix_row.to_param}, session: valid_session
      expect(response).to redirect_to(matrix_rows_url)
    end
  end

end
