require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe MatricesController, type: :controller do
  before(:each) {
    sign_in
  }

  # This should return the minimal set of attributes required to create a valid
  # Matrix. As you add validations to Matrix, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    strip_housekeeping_attributes(FactoryGirl.build(:valid_matrix).attributes)  
  }

  let(:invalid_attributes) {
    {name: nil} 
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # MatricesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns matrices as @recent_objects" do
      matrix = Matrix.create! valid_attributes
      get :index, {}, session: valid_session
      expect(assigns(:recent_objects)).to eq([matrix])
    end
  end

  describe "GET #show" do
    it "assigns the requested matrix as @matrix" do
      matrix = Matrix.create! valid_attributes
      get :show, {id: matrix.to_param}
      expect(assigns(:matrix)).to eq(matrix)
    end
  end

  describe "GET #new" do
    it "assigns a new matrix as @matrix" do
      get :new, {}, session: valid_session
      expect(assigns(:matrix)).to be_a_new(Matrix)
    end
  end

  describe "GET #edit" do
    it "assigns the requested matrix as @matrix" do
      matrix = Matrix.create! valid_attributes
      get :edit, {id: matrix.to_param}, session: valid_session
      expect(assigns(:matrix)).to eq(matrix)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Matrix" do
        expect {
          post :create, {matrix: valid_attributes}, session: valid_session
        }.to change(Matrix, :count).by(1)
      end

      it "assigns a newly created matrix as @matrix" do
        post :create, {matrix: valid_attributes}, session: valid_session
        expect(assigns(:matrix)).to be_a(Matrix)
        expect(assigns(:matrix)).to be_persisted
      end

      it "redirects to the created matrix" do
        post :create,  {matrix: valid_attributes}, session: valid_session
        expect(response).to redirect_to(Matrix.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved matrix as @matrix" do
        post :create, {matrix: invalid_attributes}, session: valid_session
        expect(assigns(:matrix)).to be_a_new(Matrix)
      end

      it "re-renders the 'new' template" do
        post :create, {matrix: invalid_attributes}, session: valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested matrix" do
        matrix = Matrix.create! valid_attributes
        put :update, {id: matrix.to_param, matrix: new_attributes}, session: valid_session
        matrix.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested matrix as @matrix" do
        matrix = Matrix.create! valid_attributes
        put :update, {id: matrix.to_param, matrix: valid_attributes}, session: valid_session
        expect(assigns(:matrix)).to eq(matrix)
      end

      it "redirects to the matrix" do
        matrix = Matrix.create! valid_attributes
        put :update, {id: matrix.to_param, matrix: valid_attributes}, session: valid_session
        expect(response).to redirect_to(matrix)
      end
    end

    context "with invalid params" do
      it "assigns the matrix as @matrix" do
        matrix = Matrix.create! valid_attributes
        put :update, {id: matrix.to_param, matrix: invalid_attributes}, session: valid_session
        expect(assigns(:matrix)).to eq(matrix)
      end

      it "re-renders the 'edit' template" do
        matrix = Matrix.create! valid_attributes
        put :update, {id: matrix.to_param, matrix: invalid_attributes}, session: valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested matrix" do
      matrix = Matrix.create! valid_attributes
      expect {
        delete :destroy, {id: matrix.to_param}, session: valid_session
      }.to change(Matrix, :count).by(-1)
    end

    it "redirects to the matrices list" do
      matrix = Matrix.create! valid_attributes
      delete :destroy, {id: matrix.to_param}, session: valid_session
      expect(response).to redirect_to(matrices_url)
    end
  end

end
