require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe MatrixColumnsController, type: :controller do
  before(:each) {
    sign_in 
  }


  # This should return the minimal set of attributes required to create a valid
  # MatrixColumn. As you add validations to MatrixColumn, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    strip_housekeeping_attributes(FactoryGirl.build(:valid_matrix_column).attributes)
  }

  let(:invalid_attributes) {
    valid_attributes.merge(matrix_id: nil)
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # MatrixColumnsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns recent matrix_columns as @recent_objects" do
      matrix_column = MatrixColumn.create! valid_attributes
      get :index, {}, session: valid_session
      expect(assigns(:recent_objects)).to eq([matrix_column])
    end
  end

  describe "GET #show" do
    it "assigns the requested matrix_column as @matrix_column" do
      matrix_column = MatrixColumn.create! valid_attributes
      get :show, {id: matrix_column.to_param}, session: valid_session
      expect(assigns(:matrix_column)).to eq(matrix_column)
    end
  end

  describe "GET #new" do
    it "assigns a new matrix_column as @matrix_column" do
      get :new, {}, session: valid_session
      expect(assigns(:matrix_column)).to be_a_new(MatrixColumn)
    end
  end

  describe "GET #edit" do
    it "assigns the requested matrix_column as @matrix_column" do
      matrix_column = MatrixColumn.create! valid_attributes
      get :edit, {id: matrix_column.to_param}, session: valid_session
      expect(assigns(:matrix_column)).to eq(matrix_column)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new MatrixColumn" do
        expect {
          post :create, {matrix_column: valid_attributes}, session: valid_session
        }.to change(MatrixColumn, :count).by(1)
      end

      it "assigns a newly created matrix_column as @matrix_column" do
        post :create, {matrix_column: valid_attributes}, session: valid_session
        expect(assigns(:matrix_column)).to be_a(MatrixColumn)
        expect(assigns(:matrix_column)).to be_persisted
      end

      it "redirects to the created matrix_column" do
        post :create, {matrix_column: valid_attributes}, session: valid_session
        expect(response).to redirect_to(MatrixColumn.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved matrix_column as @matrix_column" do
        post :create, {matrix_column: invalid_attributes}, session: valid_session
        expect(assigns(:matrix_column)).to be_a_new(MatrixColumn)
      end

      it "re-renders the 'new' template" do
        post :create, {matrix_column: invalid_attributes}, session: valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested matrix_column" do
        matrix_column = MatrixColumn.create! valid_attributes
        m = Matrix.create!(name: 'foo')
        put :update, {id: matrix_column.to_param, matrix_column: {matrix_id: m.to_param}}, session: valid_session
        matrix_column.reload
        expect(matrix_column.matrix_id).to eq(m.id) 
      end

      it "assigns the requested matrix_column as @matrix_column" do
        matrix_column = MatrixColumn.create! valid_attributes
        put :update, {id: matrix_column.to_param, matrix_column: valid_attributes}, session: valid_session
        expect(assigns(:matrix_column)).to eq(matrix_column)
      end

      it "redirects to the matrix_column" do
        matrix_column = MatrixColumn.create! valid_attributes
        put :update, {id: matrix_column.to_param, matrix_column: valid_attributes}, session: valid_session
        expect(response).to redirect_to(matrix_column)
      end
    end

    context "with invalid params" do
      it "assigns the matrix_column as @matrix_column" do
        matrix_column = MatrixColumn.create! valid_attributes
        put :update, {id: matrix_column.to_param, matrix_column: invalid_attributes}, session: valid_session
        expect(assigns(:matrix_column)).to eq(matrix_column)
      end

      it "re-renders the 'edit' template" do
        matrix_column = MatrixColumn.create! valid_attributes
        put :update, {id: matrix_column.to_param, matrix_column: invalid_attributes}, session: valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested matrix_column" do
      matrix_column = MatrixColumn.create! valid_attributes
      expect {
        delete :destroy, {id: matrix_column.to_param}, session: valid_session
      }.to change(MatrixColumn, :count).by(-1)
    end

    it "redirects to the matrix_columns list" do
      matrix_column = MatrixColumn.create! valid_attributes
      delete :destroy, {id: matrix_column.to_param}, session: valid_session
      expect(response).to redirect_to(matrix_columns_url)
    end
  end

end
