require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PublicContentsController, type: :controller do
  before(:each) {
    sign_in
  }

  # This should return the minimal set of attributes required to create a valid
  # PublicContent. As you add validations to PublicContent, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { 
    t = FactoryBot.create(:valid_topic)   
    c = FactoryBot.create(:valid_content, topic: t)
    FactoryBot.build(:valid_public_content, topic: t, content: c).attributes 
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PublicContentsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  before {
    request.env['HTTP_REFERER'] = list_otus_path # logical example
  }

  describe 'POST create' do
    describe 'with valid params' do
      it 'creates a new PublicContent' do
        expect {
          post :create, params: {public_content: valid_attributes}, session: valid_session
        }.to change(PublicContent, :count).by(1)
      end

      it 'assigns a newly created public_content as @public_content' do
        post :create, params: {public_content: valid_attributes}, session: valid_session
        expect(assigns(:public_content)).to be_a(PublicContent)
        expect(assigns(:public_content)).to be_persisted
      end

      it 'redirects to :back' do
        post :create, params: {public_content: valid_attributes}, session: valid_session
        expect(response).to redirect_to(list_otus_path)
      end
    end

    describe 'with invalid params' do
      it 'assigns a newly created but unsaved public_content as @public_content' do
        # Trigger the behavior that occurs when invalid params are submitted
        allow_any_instance_of(PublicContent).to receive(:save).and_return(false)
        post :create, params: {public_content: {invalid: 'parms'}}, session: valid_session
        expect(assigns(:public_content)).to be_a_new(PublicContent)
      end

      it 're-renders the :back template' do
        # Trigger the behavior that occurs when invalid params are submitted
        allow_any_instance_of(PublicContent).to receive(:save).and_return(false)
        post :create, params: {public_content: {invalid: 'parms'}}, session: valid_session
        expect(response).to redirect_to(list_otus_path)
      end
    end
  end

  describe 'PUT update' do
    describe 'with valid params' do
      it 'updates the requested public_content' do
        public_content = PublicContent.create! valid_attributes
        # Assuming there are no other public_contents in the database, this
        # specifies that the PublicContent created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        update_params = ActionController::Parameters.new({text: 'New text'}).permit(:text)
        expect_any_instance_of(PublicContent).to receive(:update).with(update_params)
        put :update, params: {id: public_content.to_param, public_content: update_params}, session: valid_session
      end

      it 'assigns the requested public_content as @public_content' do
        public_content = PublicContent.create! valid_attributes
        put :update, params: {id: public_content.to_param, public_content: valid_attributes}, session: valid_session
        expect(assigns(:public_content)).to eq(public_content)
      end

      it 'redirects to :back' do
        public_content = PublicContent.create! valid_attributes
        put :update, params: {id: public_content.to_param, public_content: valid_attributes}, session: valid_session
        expect(response).to redirect_to(list_otus_path)
      end
    end

    describe 'with invalid params' do
      it 'assigns the public_content as @public_content' do
        public_content = PublicContent.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        allow_any_instance_of(PublicContent).to receive(:save).and_return(false)
        put :update, params: {id: public_content.to_param, public_content: {foo: 'bar'}}, session: valid_session
        expect(assigns(:public_content)).to eq(public_content)
      end

      it 're-renders the :back template' do
        public_content = PublicContent.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        allow_any_instance_of(PublicContent).to receive(:save).and_return(false)
        put :update, params: {id: public_content.to_param, public_content: {foo: 'bar'}}, session: valid_session
        expect(response).to redirect_to(list_otus_path)
      end
    end
  end

  describe 'DELETE destroy' do
    it 'destroys the requested public_content' do
      public_content = PublicContent.create! valid_attributes
      expect {
        delete :destroy, params: {id: public_content.to_param}, session: valid_session
      }.to change(PublicContent, :count).by(-1)
    end

    it 'redirects to :back' do
      public_content = PublicContent.create! valid_attributes
      delete :destroy, params: {id: public_content.to_param}, session: valid_session
      expect(response).to redirect_to(list_otus_path)
    end
  end

end
