require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe RepositoriesController do

  # This should return the minimal set of attributes required to create a valid
  # Repository. As you add validations to Repository, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # RepositoriesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all repositories as @repositories" do
      repository = Repository.create! valid_attributes
      get :index, {}, valid_session
      assigns(:repositories).should eq([repository])
    end
  end

  describe "GET show" do
    it "assigns the requested repository as @repository" do
      repository = Repository.create! valid_attributes
      get :show, {:id => repository.to_param}, valid_session
      assigns(:repository).should eq(repository)
    end
  end

  describe "GET new" do
    it "assigns a new repository as @repository" do
      get :new, {}, valid_session
      assigns(:repository).should be_a_new(Repository)
    end
  end

  describe "GET edit" do
    it "assigns the requested repository as @repository" do
      repository = Repository.create! valid_attributes
      get :edit, {:id => repository.to_param}, valid_session
      assigns(:repository).should eq(repository)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Repository" do
        expect {
          post :create, {:repository => valid_attributes}, valid_session
        }.to change(Repository, :count).by(1)
      end

      it "assigns a newly created repository as @repository" do
        post :create, {:repository => valid_attributes}, valid_session
        assigns(:repository).should be_a(Repository)
        assigns(:repository).should be_persisted
      end

      it "redirects to the created repository" do
        post :create, {:repository => valid_attributes}, valid_session
        response.should redirect_to(Repository.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved repository as @repository" do
        # Trigger the behavior that occurs when invalid params are submitted
        Repository.any_instance.stub(:save).and_return(false)
        post :create, {:repository => { "name" => "invalid value" }}, valid_session
        assigns(:repository).should be_a_new(Repository)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Repository.any_instance.stub(:save).and_return(false)
        post :create, {:repository => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested repository" do
        repository = Repository.create! valid_attributes
        # Assuming there are no other repositories in the database, this
        # specifies that the Repository created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Repository.any_instance.should_receive(:update).with({ "name" => "MyString" })
        put :update, {:id => repository.to_param, :repository => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested repository as @repository" do
        repository = Repository.create! valid_attributes
        put :update, {:id => repository.to_param, :repository => valid_attributes}, valid_session
        assigns(:repository).should eq(repository)
      end

      it "redirects to the repository" do
        repository = Repository.create! valid_attributes
        put :update, {:id => repository.to_param, :repository => valid_attributes}, valid_session
        response.should redirect_to(repository)
      end
    end

    describe "with invalid params" do
      it "assigns the repository as @repository" do
        repository = Repository.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Repository.any_instance.stub(:save).and_return(false)
        put :update, {:id => repository.to_param, :repository => { "name" => "invalid value" }}, valid_session
        assigns(:repository).should eq(repository)
      end

      it "re-renders the 'edit' template" do
        repository = Repository.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Repository.any_instance.stub(:save).and_return(false)
        put :update, {:id => repository.to_param, :repository => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested repository" do
      repository = Repository.create! valid_attributes
      expect {
        delete :destroy, {:id => repository.to_param}, valid_session
      }.to change(Repository, :count).by(-1)
    end

    it "redirects to the repositories list" do
      repository = Repository.create! valid_attributes
      delete :destroy, {:id => repository.to_param}, valid_session
      response.should redirect_to(repositories_url)
    end
  end

end
