require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe SequencesController, type: :controller do
  before(:each){
    sign_in
  }
  # This should return the minimal set of attributes required to create a valid
  # Sequence. As you add validations to Sequence, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    strip_housekeeping_attributes(FactoryGirl.build(:valid_sequence).attributes)
  }

  let(:invalid_attributes) {
    {sequence: nil, sequence_type: ""}
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # SequencesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all sequences as @sequences" do
      sequence = Sequence.create! valid_attributes
      get :index, {}, session: valid_session
      expect(assigns(:recent_objects)).to eq([sequence])
    end
  end

  describe "GET #show" do
    it "assigns the requested sequence as @sequence" do
      sequence = Sequence.create! valid_attributes
      get :show, {id: sequence.to_param}, session: valid_session
      expect(assigns(:sequence)).to eq(sequence)
    end
  end

  describe "GET #new" do
    it "assigns a new sequence as @sequence" do
      get :new, {}, session: valid_session
      expect(assigns(:sequence)).to be_a_new(Sequence)
    end
  end

  describe "GET #edit" do
    it "assigns the requested sequence as @sequence" do
      sequence = Sequence.create! valid_attributes
      get :edit, {id: sequence.to_param}, session: valid_session
      expect(assigns(:sequence)).to eq(sequence)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Sequence" do
        expect {
          post :create, {sequence: valid_attributes}, session: valid_session
        }.to change(Sequence, :count).by(1)
      end

      it "assigns a newly created sequence as @sequence" do
        post :create, {sequence: valid_attributes}, session: valid_session
        expect(assigns(:sequence)).to be_a(Sequence)
        expect(assigns(:sequence)).to be_persisted
      end

      it "redirects to the created sequence" do
        post :create, {sequence: valid_attributes}, session: valid_session
        expect(response).to redirect_to(Sequence.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved sequence as @sequence" do
        post :create, {sequence: invalid_attributes}, session: valid_session
        expect(assigns(:sequence)).to be_a_new(Sequence)
      end

      it "re-renders the 'new' template" do
        post :create, {sequence: invalid_attributes}, session: valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        { sequence_type: "DNA", sequence: "random sequence" }
      }

      it "updates the requested sequence" do
        sequence = Sequence.create! valid_attributes
        put :update, {id: sequence.to_param, sequence: new_attributes}, session: valid_session
        sequence.reload

        expect(sequence.sequence == new_attributes[:sequence])
      end

      it "assigns the requested sequence as @sequence" do
        sequence = Sequence.create! valid_attributes
        put :update, {id: sequence.to_param, sequence: valid_attributes}, session: valid_session
        expect(assigns(:sequence)).to eq(sequence)
      end

      it "redirects to the sequence" do
        sequence = Sequence.create! valid_attributes
        put :update, {id: sequence.to_param, sequence: valid_attributes}, session: valid_session
        expect(response).to redirect_to(sequence)
      end
    end

    context "with invalid params" do
      it "assigns the sequence as @sequence" do
        sequence = Sequence.create! valid_attributes
        put :update, {id: sequence.to_param, sequence: invalid_attributes}, session: valid_session
        expect(assigns(:sequence)).to eq(sequence)
      end

      it "re-renders the 'edit' template" do
        sequence = Sequence.create! valid_attributes
        put :update, {id: sequence.to_param, sequence: invalid_attributes}, session: valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested sequence" do
      sequence = Sequence.create! valid_attributes
      expect {
        delete :destroy, {id: sequence.to_param}, session: valid_session
      }.to change(Sequence, :count).by(-1)
    end

    it "redirects to the sequences list" do
      sequence = Sequence.create! valid_attributes
      delete :destroy, {id: sequence.to_param}, session: valid_session
      expect(response).to redirect_to(sequences_url)
    end
  end

end
