require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe TaggedSectionKeywordsController do
  before(:each) {
    sign_in
  }

  # This should return the minimal set of attributes required to create a valid
  # TaggedSectionKeyword. As you add validations to TaggedSectionKeyword, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { strip_housekeeping_attributes(FactoryGirl.build(:valid_tagged_section_keyword).attributes) }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # TaggedSectionKeywordsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all tagged_section_keywords as @tagged_section_keywords" do
      tagged_section_keyword = TaggedSectionKeyword.create! valid_attributes
      get :index, {}, valid_session
      assigns(:tagged_section_keywords).should eq([tagged_section_keyword])
    end
  end

  describe "GET show" do
    it "assigns the requested tagged_section_keyword as @tagged_section_keyword" do
      tagged_section_keyword = TaggedSectionKeyword.create! valid_attributes
      get :show, {:id => tagged_section_keyword.to_param}, valid_session
      assigns(:tagged_section_keyword).should eq(tagged_section_keyword)
    end
  end

  describe "GET new" do
    it "assigns a new tagged_section_keyword as @tagged_section_keyword" do
      get :new, {}, valid_session
      assigns(:tagged_section_keyword).should be_a_new(TaggedSectionKeyword)
    end
  end

  describe "GET edit" do
    it "assigns the requested tagged_section_keyword as @tagged_section_keyword" do
      tagged_section_keyword = TaggedSectionKeyword.create! valid_attributes
      get :edit, {:id => tagged_section_keyword.to_param}, valid_session
      assigns(:tagged_section_keyword).should eq(tagged_section_keyword)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new TaggedSectionKeyword" do
        expect {
          post :create, {:tagged_section_keyword => valid_attributes}, valid_session
        }.to change(TaggedSectionKeyword, :count).by(1)
      end

      it "assigns a newly created tagged_section_keyword as @tagged_section_keyword" do
        post :create, {:tagged_section_keyword => valid_attributes}, valid_session
        assigns(:tagged_section_keyword).should be_a(TaggedSectionKeyword)
        assigns(:tagged_section_keyword).should be_persisted
      end

      it "redirects to the created tagged_section_keyword" do
        post :create, {:tagged_section_keyword => valid_attributes}, valid_session
        response.should redirect_to(TaggedSectionKeyword.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved tagged_section_keyword as @tagged_section_keyword" do
        # Trigger the behavior that occurs when invalid params are submitted
        TaggedSectionKeyword.any_instance.stub(:save).and_return(false)
        post :create, {:tagged_section_keyword => {:invalid => 'parms'}}, valid_session
        assigns(:tagged_section_keyword).should be_a_new(TaggedSectionKeyword)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        TaggedSectionKeyword.any_instance.stub(:save).and_return(false)
        post :create, {:tagged_section_keyword => {:invalid => 'parms'}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe 'PUT update' do
    describe 'with valid params' do
      it 'updates the requested tagged_section_keyword' do
        tagged_section_keyword = TaggedSectionKeyword.create! valid_attributes
        # Assuming there are no other tagged_section_keywords in the database, this
        # specifies that the TaggedSectionKeyword created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        opls = FactoryGirl.create(:valid_otu_page_layout_section)
        TaggedSectionKeyword.any_instance.should_receive(:update).with({'otu_page_layout_section_id' => opls.id.to_s})
        put :update, {:id => tagged_section_keyword.to_param, :tagged_section_keyword => {keyword_id: opls.id}}, valid_session
      end

      it "assigns the requested tagged_section_keyword as @tagged_section_keyword" do
        tagged_section_keyword = TaggedSectionKeyword.create! valid_attributes
        put :update, {:id => tagged_section_keyword.to_param, :tagged_section_keyword => valid_attributes}, valid_session
        assigns(:tagged_section_keyword).should eq(tagged_section_keyword)
      end

      it "redirects to the tagged_section_keyword" do
        tagged_section_keyword = TaggedSectionKeyword.create! valid_attributes
        put :update, {:id => tagged_section_keyword.to_param, :tagged_section_keyword => valid_attributes}, valid_session
        response.should redirect_to(tagged_section_keyword)
      end
    end

    describe "with invalid params" do
      it "assigns the tagged_section_keyword as @tagged_section_keyword" do
        tagged_section_keyword = TaggedSectionKeyword.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        TaggedSectionKeyword.any_instance.stub(:save).and_return(false)
        put :update, {:id => tagged_section_keyword.to_param, :tagged_section_keyword => {:invalid => 'parms'}}, valid_session
        assigns(:tagged_section_keyword).should eq(tagged_section_keyword)
      end

      it "re-renders the 'edit' template" do
        tagged_section_keyword = TaggedSectionKeyword.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        TaggedSectionKeyword.any_instance.stub(:save).and_return(false)
        put :update, {:id => tagged_section_keyword.to_param, :tagged_section_keyword => {:invalid => 'parms'}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested tagged_section_keyword" do
      tagged_section_keyword = TaggedSectionKeyword.create! valid_attributes
      expect {
        delete :destroy, {:id => tagged_section_keyword.to_param}, valid_session
      }.to change(TaggedSectionKeyword, :count).by(-1)
    end

    it "redirects to the tagged_section_keywords list" do
      tagged_section_keyword = TaggedSectionKeyword.create! valid_attributes
      delete :destroy, {:id => tagged_section_keyword.to_param}, valid_session
      response.should redirect_to(tagged_section_keywords_url)
    end
  end

end
