require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe TaxonDeterminationsController do

  # This should return the minimal set of attributes required to create a valid
  # TaxonDetermination. As you add validations to TaxonDetermination, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "biological_collection_object_id" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # TaxonDeterminationsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all taxon_determinations as @taxon_determinations" do
      taxon_determination = TaxonDetermination.create! valid_attributes
      get :index, {}, valid_session
      assigns(:taxon_determinations).should eq([taxon_determination])
    end
  end

  describe "GET show" do
    it "assigns the requested taxon_determination as @taxon_determination" do
      taxon_determination = TaxonDetermination.create! valid_attributes
      get :show, {:id => taxon_determination.to_param}, valid_session
      assigns(:taxon_determination).should eq(taxon_determination)
    end
  end

  describe "GET new" do
    it "assigns a new taxon_determination as @taxon_determination" do
      get :new, {}, valid_session
      assigns(:taxon_determination).should be_a_new(TaxonDetermination)
    end
  end

  describe "GET edit" do
    it "assigns the requested taxon_determination as @taxon_determination" do
      taxon_determination = TaxonDetermination.create! valid_attributes
      get :edit, {:id => taxon_determination.to_param}, valid_session
      assigns(:taxon_determination).should eq(taxon_determination)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new TaxonDetermination" do
        expect {
          post :create, {:taxon_determination => valid_attributes}, valid_session
        }.to change(TaxonDetermination, :count).by(1)
      end

      it "assigns a newly created taxon_determination as @taxon_determination" do
        post :create, {:taxon_determination => valid_attributes}, valid_session
        assigns(:taxon_determination).should be_a(TaxonDetermination)
        assigns(:taxon_determination).should be_persisted
      end

      it "redirects to the created taxon_determination" do
        post :create, {:taxon_determination => valid_attributes}, valid_session
        response.should redirect_to(TaxonDetermination.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved taxon_determination as @taxon_determination" do
        # Trigger the behavior that occurs when invalid params are submitted
        TaxonDetermination.any_instance.stub(:save).and_return(false)
        post :create, {:taxon_determination => { "biological_collection_object_id" => "invalid value" }}, valid_session
        assigns(:taxon_determination).should be_a_new(TaxonDetermination)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        TaxonDetermination.any_instance.stub(:save).and_return(false)
        post :create, {:taxon_determination => { "biological_collection_object_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested taxon_determination" do
        taxon_determination = TaxonDetermination.create! valid_attributes
        # Assuming there are no other taxon_determinations in the database, this
        # specifies that the TaxonDetermination created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        TaxonDetermination.any_instance.should_receive(:update).with({ "biological_collection_object_id" => "1" })
        put :update, {:id => taxon_determination.to_param, :taxon_determination => { "biological_collection_object_id" => "1" }}, valid_session
      end

      it "assigns the requested taxon_determination as @taxon_determination" do
        taxon_determination = TaxonDetermination.create! valid_attributes
        put :update, {:id => taxon_determination.to_param, :taxon_determination => valid_attributes}, valid_session
        assigns(:taxon_determination).should eq(taxon_determination)
      end

      it "redirects to the taxon_determination" do
        taxon_determination = TaxonDetermination.create! valid_attributes
        put :update, {:id => taxon_determination.to_param, :taxon_determination => valid_attributes}, valid_session
        response.should redirect_to(taxon_determination)
      end
    end

    describe "with invalid params" do
      it "assigns the taxon_determination as @taxon_determination" do
        taxon_determination = TaxonDetermination.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        TaxonDetermination.any_instance.stub(:save).and_return(false)
        put :update, {:id => taxon_determination.to_param, :taxon_determination => { "biological_collection_object_id" => "invalid value" }}, valid_session
        assigns(:taxon_determination).should eq(taxon_determination)
      end

      it "re-renders the 'edit' template" do
        taxon_determination = TaxonDetermination.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        TaxonDetermination.any_instance.stub(:save).and_return(false)
        put :update, {:id => taxon_determination.to_param, :taxon_determination => { "biological_collection_object_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested taxon_determination" do
      taxon_determination = TaxonDetermination.create! valid_attributes
      expect {
        delete :destroy, {:id => taxon_determination.to_param}, valid_session
      }.to change(TaxonDetermination, :count).by(-1)
    end

    it "redirects to the taxon_determinations list" do
      taxon_determination = TaxonDetermination.create! valid_attributes
      delete :destroy, {:id => taxon_determination.to_param}, valid_session
      response.should redirect_to(taxon_determinations_url)
    end
  end

end
