require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe TaxonNameClassificationsController, :type => :controller do
  before(:each) {
    sign_in 
  }

  # This should return the minimal set of attributes required to create a valid
  # Georeference. As you add validations to Georeference be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { 
    strip_housekeeping_attributes( FactoryGirl.build(:valid_taxon_name_classification).attributes )
  }  

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # TaxonNameClassificationsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all taxon_name_classifications as @taxon_name_classifications" do
      taxon_name_classification = TaxonNameClassification.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:taxon_name_classifications)).to eq([taxon_name_classification])
    end
  end

  describe "GET show" do
    it "assigns the requested taxon_name_classification as @taxon_name_classification" do
      taxon_name_classification = TaxonNameClassification.create! valid_attributes
      get :show, {:id => taxon_name_classification.to_param}, valid_session
      expect(assigns(:taxon_name_classification)).to eq(taxon_name_classification)
    end
  end

  describe "GET new" do
    it "assigns a new taxon_name_classification as @taxon_name_classification" do
      get :new, {}, valid_session
      expect(assigns(:taxon_name_classification)).to be_a_new(TaxonNameClassification)
    end
  end

  describe "GET edit" do
    it "assigns the requested taxon_name_classification as @taxon_name_classification" do
      taxon_name_classification = TaxonNameClassification.create! valid_attributes
      get :edit, {:id => taxon_name_classification.to_param}, valid_session
      expect(assigns(:taxon_name_classification)).to eq(taxon_name_classification)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new TaxonNameClassification" do
        expect {
          post :create, {:taxon_name_classification => valid_attributes}, valid_session
        }.to change(TaxonNameClassification, :count).by(1)
      end

      it "assigns a newly created taxon_name_classification as @taxon_name_classification" do
        post :create, {:taxon_name_classification => valid_attributes}, valid_session
        expect(assigns(:taxon_name_classification)).to be_a(TaxonNameClassification)
        expect(assigns(:taxon_name_classification)).to be_persisted
      end

      it "redirects to the created taxon_name_classification" do
        post :create, {:taxon_name_classification => valid_attributes}, valid_session
        expect(response).to redirect_to(TaxonNameClassification.last.becomes(TaxonNameClassification))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved taxon_name_classification as @taxon_name_classification" do
        # Trigger the behavior that occurs when invalid params are submitted
        allow_any_instance_of(TaxonNameClassification).to receive(:save).and_return(false)
        post :create, {:taxon_name_classification => { "taxon_name_id" => "invalid value" }}, valid_session
        expect(assigns(:taxon_name_classification)).to be_a_new(TaxonNameClassification)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        allow_any_instance_of(TaxonNameClassification).to receive(:save).and_return(false)
        post :create, {:taxon_name_classification => { "taxon_name_id" => "invalid value" }}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested taxon_name_classification" do
        taxon_name_classification = TaxonNameClassification.create! valid_attributes
        # Assuming there are no other taxon_name_classifications in the database, this
        # specifies that the TaxonNameClassification created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        expect_any_instance_of(TaxonNameClassification).to receive(:update).with({ "taxon_name_id" => "1" })
        put :update, {:id => taxon_name_classification.to_param, :taxon_name_classification => { "taxon_name_id" => "1" }}, valid_session
      end

      it "assigns the requested taxon_name_classification as @taxon_name_classification" do
        taxon_name_classification = TaxonNameClassification.create! valid_attributes
        put :update, {:id => taxon_name_classification.to_param, :taxon_name_classification => valid_attributes}, valid_session
        expect(assigns(:taxon_name_classification)).to eq(taxon_name_classification)
      end

      it "redirects to the taxon_name_classification" do
        taxon_name_classification = TaxonNameClassification.create! valid_attributes
        put :update, {:id => taxon_name_classification.to_param, :taxon_name_classification => valid_attributes}, valid_session
        expect(response).to redirect_to(taxon_name_classification.becomes(TaxonNameClassification))
      end
    end

    describe "with invalid params" do
      it "assigns the taxon_name_classification as @taxon_name_classification" do
        taxon_name_classification = TaxonNameClassification.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        allow_any_instance_of(TaxonNameClassification).to receive(:save).and_return(false)
        put :update, {:id => taxon_name_classification.to_param, :taxon_name_classification => { "taxon_name_id" => "invalid value" }}, valid_session
        expect(assigns(:taxon_name_classification)).to eq(taxon_name_classification)
      end

      it "re-renders the 'edit' template" do
        taxon_name_classification = TaxonNameClassification.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        allow_any_instance_of(TaxonNameClassification).to receive(:save).and_return(false)
        put :update, {:id => taxon_name_classification.to_param, :taxon_name_classification => { "taxon_name_id" => "invalid value" }}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested taxon_name_classification" do
      taxon_name_classification = TaxonNameClassification.create! valid_attributes
      expect {
        delete :destroy, {:id => taxon_name_classification.to_param}, valid_session
      }.to change(TaxonNameClassification, :count).by(-1)
    end

    it "redirects to the taxon_name_classifications list" do
      taxon_name_classification = TaxonNameClassification.create! valid_attributes
      delete :destroy, {:id => taxon_name_classification.to_param}, valid_session
      expect(response).to redirect_to(taxon_name_classifications_url)
    end
  end

end
