require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe TaxonNamesController, :type => :controller do
  before(:each) {
    sign_in
  }

  # This should return the minimal set of attributes required to create a valid
  # Georeference. As you add validations to Georeference be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { strip_housekeeping_attributes(FactoryGirl.build(:valid_taxon_name).attributes)
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # TaxonNamesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET list" do
    it "with no other parameters, assigns 20/page taxon_names as @taxon_names" do
      taxon_name = TaxonName.create! valid_attributes
      get :list, {}, valid_session
      expect(assigns(:taxon_names)).to include(taxon_name.becomes(taxon_name.type.constantize))
    end

    it "renders the list template" do
      get :list, {}, valid_session
      expect(response).to render_template("list")
    end
  end

  describe "GET index" do
    it "assigns all taxon_names as @taxon_names" do
      taxon_name = TaxonName.create!(valid_attributes)
      get :index, {}, valid_session
      # The following means that @taxon_names = TaxonName.all in the controller.
      # todo @mjy following line (coming from Otu) is slightly different than others, i.e. others eq(taxon_name)
      expect(assigns(:recent_objects)).to include(taxon_name.becomes(taxon_name.type.constantize))
    end
  end

  describe "GET show" do
    it "assigns the requested taxon_name as @taxon_name" do
      taxon_name = TaxonName.create! valid_attributes
      get :show, {:id => taxon_name.to_param}, valid_session
      expect(assigns(:taxon_name)).to eq(taxon_name.becomes(taxon_name.type.constantize))
    end
  end

  describe "GET new" do
    it "assigns a new taxon_name as @taxon_name" do
      get :new, {}, valid_session
      expect(assigns(:taxon_name)).to be_a_new(TaxonName)
    end
  end

  describe "GET edit" do
    it "assigns the requested taxon_name as @taxon_name" do
      taxon_name = TaxonName.create! valid_attributes
      get :edit, {:id => taxon_name.to_param}, valid_session
      expect(assigns(:taxon_name)).to eq(taxon_name.becomes(taxon_name.type.constantize))
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new TaxonName" do
        expect {
          post :create, {:taxon_name => valid_attributes}, valid_session
        }.to change(TaxonName, :count).by(2) # both root and a name are created
      end

      it "assigns a newly created taxon_name as @taxon_name" do
        post :create, {:taxon_name => valid_attributes}, valid_session
        expect(assigns(:taxon_name)).to be_a(TaxonName)
        expect(assigns(:taxon_name)).to be_persisted
      end

      it "redirects to the created taxon_name" do
        post :create, {:taxon_name => valid_attributes}, valid_session
        expect(response).to redirect_to(TaxonName.last.becomes(TaxonName))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved taxon_name as @taxon_name" do
        # Trigger the behavior that occurs when invalid params are submitted
        allow_any_instance_of(TaxonName).to receive(:save).and_return(false)
        post :create, {:taxon_name => {"name" => "invalid value"}}, valid_session
        expect(assigns(:taxon_name)).to be_a_new(TaxonName)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        allow_any_instance_of(TaxonName).to receive(:save).and_return(false)
        post :create, {:taxon_name => {"name" => "invalid value"}}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested taxon_name" do
        taxon_name = TaxonName.create! valid_attributes
        # Assuming there are no other taxon_names in the database, this
        # specifies that the TaxonName created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        expect_any_instance_of(TaxonName).to receive(:update).with({"name" => "MyString"})
        put :update, {:id => taxon_name.to_param, :taxon_name => {"name" => "MyString"}}, valid_session
      end

      it "assigns the requested taxon_name as @taxon_name" do
        taxon_name = TaxonName.create! valid_attributes
        put :update, {:id => taxon_name.to_param, :taxon_name => valid_attributes}, valid_session
        expect(assigns(:taxon_name)).to eq(taxon_name.becomes(taxon_name.type.constantize))
      end

      it "redirects to the taxon_name" do
        taxon_name = TaxonName.create! valid_attributes
        put :update, {:id => taxon_name.to_param, :taxon_name => valid_attributes}, valid_session
        expect(response).to redirect_to(taxon_name.becomes(TaxonName))
      end
    end

    describe "with invalid params" do
      it "assigns the taxon_name as @taxon_name" do
        taxon_name = TaxonName.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        allow_any_instance_of(TaxonName).to receive(:save).and_return(false)
        put :update, {:id => taxon_name.to_param, :taxon_name => {"name" => "invalid value"}}, valid_session
        expect(assigns(:taxon_name)).to eq(taxon_name.becomes(taxon_name.type.constantize))
      end

      it "re-renders the 'edit' template" do
        taxon_name = TaxonName.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        allow_any_instance_of(TaxonName).to receive(:save).and_return(false)
        put :update, {:id => taxon_name.to_param, :taxon_name => {"name" => "invalid value"}}, valid_session
        expect(response).to render_template("edit")
      end
    end

    describe "DELETE destroy" do
      it "destroys the requested taxon_name" do
        taxon_name = TaxonName.create! valid_attributes
        expect {
          delete :destroy, {:id => taxon_name.to_param}, valid_session
        }.to change(TaxonName, :count).by(-1)
      end

      it "redirects to the taxon_name list" do
        taxon_name = TaxonName.create! valid_attributes
        delete :destroy, {:id => taxon_name.to_param}, valid_session
        expect(response).to redirect_to(taxon_names_url)
      end
    end

  end
end
