source 'https://rubygems.org'

gem 'webdrivers', '~> 4.5', require: false
gem 'browsermob-proxy', '~> 0.3.1'
gem 'rspec', '~> 3.8'
gem 'capybara', '~> 3.29'
gem 'webrick', '~> 1.7'
gem 'rexml', '~> 3.2', '>= 3.2.5'
gem 'rspec-steps', '~> 2.1', '>= 2.1.1'
