source 'https://rubygems.org'

gem 'selenium-webdriver', '~> 3.142', '>= 3.142.3'
gem 'geckodriver-helper', '~> 0.24.0'
gem 'browsermob-proxy', '~> 0.3.1'
gem 'rspec', '~> 3.8'
gem 'capybara', '~> 3.29'
