# Removes all COLDP issue keywords and their associated tags from a project.
#
# ~~ generated by Claude ~~
class BulkColdpIssueCleanupJob < ApplicationJob
  queue_as :coldp_export

  def perform(project_id, user_id)
    Current.user_id = user_id
    Current.project_id = project_id

    Keyword.where(project_id: project_id)
      .where('name LIKE ?', 'COLDP: %')
      .where(css_color: BulkColdpIssueTagJob::CLB_BRAND_COLOR)
      .destroy_all
  end
end
