# Fetches CLB issue data via the issues TSV endpoint and creates
# Keyword/Tag records in TaxonWorks so users can filter affected
# records using native TW filters.
#
# Downloads GET /dataset/{key}/issues (Accept: text/tsv) which returns
# one row per name usage. The TSV header declares 5 columns
# (ID, status, rank, label, issues) but data rows contain only 2
# tab-separated values:
#   - Column 1: the COLDP source ID
#   - Column 2: semicolon-separated issue keys (e.g. "DUPLICATE_NAME;SYNONYM_RANK_DIFFERS")
#
# ID format determines the TW model:
#   - Plain integer (e.g. "1000") → Otu (from Taxon.tsv where ID = Otu.id)
#   - Dashed (e.g. "1000-331311" or "10004-340318-hash") → TaxonName
#     (reified synonym; second segment is TaxonName.id)
#
# Keywords are namespaced with "COLDP: " for easy bulk cleanup.
#
# ~~ generated by Claude ~~
class BulkColdpIssueTagJob < ApplicationJob
  queue_as :coldp_export

  CLB_ISSUE_VOCAB_URL = 'https://api.checklistbank.org/vocab/issue'
  CLB_BRAND_COLOR = '#1db5e9'

  def perform(project_id, dataset_id, user_id, issue_keys: nil)
    Current.user_id = user_id
    Current.project_id = project_id

    vocab = fetch_vocab
    target_issues = issue_keys&.map { |k| k.to_s.tr('_', ' ').downcase }&.to_set

    keyword_cache = {}

    issues_data = fetch_issues_tsv(dataset_id)

    if issues_data.blank?
      Rails.logger.info("[BulkColdpIssueTagJob] No issues data returned for dataset #{dataset_id}")
      return
    end

    lines = issues_data.lines
    Rails.logger.info("[BulkColdpIssueTagJob] Parsing #{lines.count} lines for dataset #{dataset_id}")

    rows_processed = 0
    rows_skipped = 0
    tags_created = 0

    # Skip header line; parse each data line manually since the TSV
    # has fewer data columns than declared headers
    lines.drop(1).each do |line|
      fields = line.strip.split("\t", -1)
      raw_id = fields[0]
      raw_issues = fields[1]

      next if raw_id.blank? || raw_issues.blank?

      model_class, tw_id = resolve_record(raw_id)
      next unless model_class && tw_id

      tag_object = find_tag_object(model_class, tw_id, project_id)
      unless tag_object
        rows_skipped += 1
        next
      end

      rows_processed += 1

      raw_issues.split(';').each do |raw_issue_key|
        issue_key = raw_issue_key.strip.tr('_', ' ').downcase
        next if issue_key.blank?
        next if target_issues && !target_issues.include?(issue_key)

        keyword = keyword_cache[issue_key] ||= find_or_create_keyword(issue_key, vocab, project_id, user_id)
        next unless keyword

        tag = Tag.find_or_create_by(keyword: keyword, tag_object: tag_object)
        tags_created += 1 if tag&.persisted?
      rescue ActiveRecord::RecordInvalid
        # Skip duplicate or invalid tags
      end
    end

    Rails.logger.info("[BulkColdpIssueTagJob] Done. #{rows_processed} records tagged, #{rows_skipped} skipped (not found), #{tags_created} tags, #{keyword_cache.size} keywords")
  end

  private

  def fetch_vocab
    response = Faraday.get(CLB_ISSUE_VOCAB_URL)
    JSON.parse(response.body)
  rescue => e
    raise TaxonWorks::Error, "Failed to fetch CLB issue vocabulary: #{e.message}"
  end

  def fetch_issues_tsv(dataset_id)
    base_url = Colrapi.base_url || 'https://api.checklistbank.org/'
    conn = Faraday.new(url: base_url) do |f|
      f.headers['Accept'] = 'text/tsv'
      f.options.timeout = 600
      f.adapter Faraday.default_adapter
    end

    response = conn.get("dataset/#{dataset_id}/issues")

    unless response.success?
      raise TaxonWorks::Error, "CLB issues endpoint returned status #{response.status}"
    end

    response.body
  end

  # Determine the TW model and ID from the COLDP source ID.
  #
  # Plain integer (e.g. "1000") → Otu, ID = 1000
  # Dashed ID (e.g. "1000-331311" or "10004-340318-hash") → TaxonName,
  #   ID = second segment (the TaxonName.id from Synonym.tsv nameID)
  def resolve_record(raw_id)
    parts = raw_id.to_s.strip.split('-')

    if parts.length == 1
      # Plain integer — Otu from Taxon.tsv
      id = parts[0].to_i
      return nil unless id > 0
      [Otu, id]
    else
      # Reified synonym — second segment is TaxonName.id
      id = parts[1].to_i
      return nil unless id > 0
      [TaxonName, id]
    end
  end

  def find_tag_object(model_class, tw_id, project_id)
    if model_class.column_names.include?('project_id')
      model_class.find_by(id: tw_id, project_id: project_id)
    else
      model_class.find_by(id: tw_id)
    end
  end

  def find_or_create_keyword(issue_key, vocab, project_id, user_id)
    entry = vocab.find { |v| v['name'] == issue_key }
    return nil unless entry

    keyword_name = "COLDP: #{titleize_issue(entry['name'])}"

    issue_uri = "https://api.checklistbank.org/vocab/issue##{entry['name'].tr(' ', '_')}"

    Keyword.find_or_create_by!(
      name: keyword_name,
      project_id: project_id
    ) do |k|
      k.definition = entry['description'] || "CLB issue: #{entry['name']}"
      k.uri = issue_uri
      k.css_color = CLB_BRAND_COLOR
      k.by = user_id
    end
  end

  # Title-case an issue name, e.g. "synonym rank differs" → "Synonym Rank Differs"
  # Must match the issueTitle() function in IssuesTable.vue
  def titleize_issue(name)
    name.split(' ').map(&:capitalize).join(' ')
  end
end
