name: Generate Taxonworks base Docker image
on:
  workflow_dispatch:
  
  schedule:
    - cron: '0 22 * * 6'

jobs:
  base-image:

    runs-on: ubuntu-20.04
    steps:

    - name: Git checkout
      uses: actions/checkout@v2

    - name: Build the Docker image
      run: docker build -f Dockerfile.base . -t sfgrp/taxonworks-base

    - name: Login to DockerHub
      if: ${{ github.event_name != 'pull_request' }}
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Push image to DockerHub
      run: docker push sfgrp/taxonworks-base:latest
